import Link from 'next/link';
import type { Project } from '@visionqa/contracts';
import { useProjects } from '@/features/projects/project-context';

const checks = [
  { title: 'Crawl & Site Structure', description: 'Discover pages, redirects, robots and sitemap information.', href: '/qa/crawl', icon: '⌁' },
  { title: 'Links & Resources', description: 'Find broken links, images and failed resources.', href: '/qa/links-resources', icon: '↗' },
  { title: 'Visual & Responsive', description: 'Detect overlap, clipping and viewport issues.', href: '/qa/visual-responsive', icon: '▧' },
];

export function NoProjectDashboard() { return <section className="dashboard-empty-state"><div className="dashboard-empty-icon">✦</div><p className="dashboard-eyebrow">GET STARTED</p><h1 className="dashboard-page-title">Create your first project</h1><p className="dashboard-lead">Connect a website to start organizing environments and preparing focused QA checks.</p><div className="dashboard-steps">{['Create a project', 'Choose an environment', 'Run your first check'].map((item, index) => <div className="dashboard-step" key={item}><span>0{index + 1}</span><strong>{item}</strong></div>)}</div><Link className="liquid-primary dashboard-primary-cta" href="/projects/new">Create project <span>→</span></Link></section>; }

export function ProjectGettingStartedDashboard({ project }: { project: Project }) { const { selectedEnvironment } = useProjects(); const environment = selectedEnvironment ?? project.environments[0]; return <section><div className="dashboard-overview"><div><p className="dashboard-eyebrow">PROJECT OVERVIEW</p><h1 className="dashboard-page-title">{project.name}</h1><p className="dashboard-url">{environment?.baseUrl ?? project.baseUrl}</p></div><div className="dashboard-overview-meta"><span className="dashboard-meta-label">Environment</span><strong>{environment?.name ?? 'No environment'}</strong></div></div><div className="dashboard-ready-card"><div><div className="dashboard-ready-icon">✓</div><div><h2>Your project is ready.</h2><p>No QA checks have been run yet. Start with one focused check or run a full site scan.</p></div></div><div className="dashboard-ready-actions"><Link className="liquid-primary dashboard-primary-cta" href="/qa/crawl">Start first QA check <span>→</span></Link><Link className="dashboard-secondary-cta" href="/full-scan">Run Full Scan</Link></div></div><div className="dashboard-section-heading"><div><p className="dashboard-eyebrow">RECOMMENDED</p><h2>Start with a focused QA check</h2></div><span>3 available modules</span></div><div className="dashboard-check-grid">{checks.map((check) => <Link className="dashboard-check-card" href={check.href} key={check.href}><span className="dashboard-check-icon">{check.icon}</span><h3>{check.title}</h3><p>{check.description}</p><span className="dashboard-card-action">Configure <b>→</b></span></Link>)}</div></section>; }
export function ProjectHealthDashboard({ project }: { project: Project }) { return <ProjectGettingStartedDashboard project={project} />; }
