// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/forgot-password" | "/full-scan" | "/integrations" | "/issues" | "/issues/[issueId]" | "/login" | "/projects/new" | "/qa/accessibility-seo" | "/qa/browser-network" | "/qa/crawl" | "/qa/custom-checks" | "/qa/interactions-forms" | "/qa/links-resources" | "/qa/performance-compatibility" | "/qa/visual-responsive" | "/register" | "/reports" | "/reports/[reportId]" | "/scans" | "/scans/[scanId]" | "/schedules" | "/settings/environments" | "/settings/project" | "/settings/security" | "/settings/team"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/dashboard": {}
  "/forgot-password": {}
  "/full-scan": {}
  "/integrations": {}
  "/issues": {}
  "/issues/[issueId]": { "issueId": string; }
  "/login": {}
  "/projects/new": {}
  "/qa/accessibility-seo": {}
  "/qa/browser-network": {}
  "/qa/crawl": {}
  "/qa/custom-checks": {}
  "/qa/interactions-forms": {}
  "/qa/links-resources": {}
  "/qa/performance-compatibility": {}
  "/qa/visual-responsive": {}
  "/register": {}
  "/reports": {}
  "/reports/[reportId]": { "reportId": string; }
  "/scans": {}
  "/scans/[scanId]": { "scanId": string; }
  "/schedules": {}
  "/settings/environments": {}
  "/settings/project": {}
  "/settings/security": {}
  "/settings/team": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
