'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useProjects } from '@/features/projects/project-context';
import { createScan } from '@/features/scans/scan.service';
import { ScanTargetInput } from '@/features/scans/components/ScanTargetInput';
import type { Scan } from '@visionqa/contracts';

const groups = [['Accessibility', [['accessible-name', 'Accessible names'], ['form-labels', 'Form labels'], ['image-alt', 'Image alternative text'], ['heading-structure', 'Heading structure'], ['document-language', 'Document language'], ['duplicate-id', 'Duplicate IDs'], ['landmark-structure', 'Landmarks'], ['keyboard-focus', 'Keyboard focus']]], ['SEO', [['seo-title', 'Title'], ['meta-description', 'Meta description'], ['canonical', 'Canonical'], ['robots-meta', 'Robots metadata'], ['indexability', 'Indexability'], ['open-graph', 'Open Graph'], ['hreflang', 'Hreflang'], ['seo-heading-structure', 'SEO headings'], ['seo-image-alt', 'SEO image alt']]]] as const;
export default function Page() { const { selectedProject } = useProjects(); const [url, setUrl] = useState(''); const [selected, setSelected] = useState<string[]>(groups.flatMap(([, checks]) => checks.map(([id]) => id))); const [scan, setScan] = useState<Scan | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const run = async () => { if (!selectedProject || !url.trim() || !selected.length) return; setBusy(true); setError(null); try { setScan(await createScan(selectedProject.id, { url, scope: 'single-page', module: 'accessibility-seo', checks: selected, browsers: ['chromium'], viewports: [{ width: 1366, height: 768 }] })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to start the accessibility scan.'); } finally { setBusy(false); } }; return <section className="scan-page"><p className="dashboard-eyebrow">QA CHECK · ACCESSIBILITY &amp; SEO</p><h1 className="dashboard-page-title">Accessibility &amp; SEO</h1><p className="dashboard-lead">Check page structure, keyboard access, and search metadata with deterministic browser checks.</p><div className="scan-config-card"><ScanTargetInput value={url} onChange={setUrl} error={error} />{groups.map(([heading, checks]) => <fieldset key={heading}><legend>{heading}</legend>{checks.map(([id, label]) => <label className="scan-check" key={id}><input type="checkbox" checked={selected.includes(id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, id] : current.filter((item) => item !== id))} /> <span>{label}</span></label>)}</fieldset>)}{error && <p className="scan-inline-error" role="alert">{error}</p>}<button className="dashboard-primary-button" type="button" disabled={busy || !selectedProject || !url.trim() || !selected.length} onClick={() => void run()}>{busy ? 'Starting…' : 'Run accessibility check'}</button></div>{scan && <div className="scan-confirmation" role="status"><p>{scan.target?.requestedUrl}</p><Link className="dashboard-card-action" href={`/scans/${scan.id}`}>View scan →</Link></div>}</section>; }
