import { BadRequestException, Body, Controller, Delete, Get, Param, Patch, Post, Req, UseGuards } from '@nestjs/common';
import { z } from 'zod';
import type { CustomCheckDefinition, UpdateCustomCheckRequest } from '@visionqa/contracts';
import { FirebaseSessionGuard, type AuthenticatedRequest } from '../auth/firebase-session.guard.js';
import { CustomChecksService } from './custom-checks.service.js';

const definitionSchema = z.object({ targetType: z.enum(['DOM', 'TEXT', 'ATTRIBUTE', 'HTTP', 'METADATA', 'BROWSER', 'PERFORMANCE']), source: z.string().trim().min(1).max(100), selector: z.string().trim().max(300).optional(), property: z.string().trim().max(100).optional(), operator: z.enum(['EXISTS', 'NOT_EXISTS', 'EQUALS', 'NOT_EQUALS', 'CONTAINS', 'NOT_CONTAINS', 'STARTS_WITH', 'ENDS_WITH', 'GREATER_THAN', 'GREATER_OR_EQUAL', 'LESS_THAN', 'LESS_OR_EQUAL', 'COUNT_EQUALS', 'COUNT_GREATER_THAN', 'COUNT_LESS_THAN', 'VISIBLE', 'HIDDEN', 'ENABLED', 'DISABLED']), expected: z.union([z.string().max(500), z.number().finite(), z.boolean()]).optional(), options: z.object({ caseSensitive: z.boolean().optional() }).optional() });
const createSchema = z.object({ name: z.string().trim().min(1).max(120), description: z.string().trim().max(500).optional(), enabled: z.boolean().optional(), definition: definitionSchema, severity: z.enum(['critical', 'high', 'medium', 'low', 'info']) });
const updateSchema = createSchema.partial();

@Controller('api/v1/projects/:projectId/custom-checks')
@UseGuards(FirebaseSessionGuard)
export class CustomChecksController {
  constructor(private readonly customChecks: CustomChecksService) {}
  @Get() async list(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string) { return { checks: await this.customChecks.list(request.user!.id, projectId) }; }
  @Post() async create(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Body() body: unknown) { const parsed = createSchema.safeParse(body); if (!parsed.success) throw new BadRequestException('Invalid custom check definition.'); const data = parsed.data; return { check: await this.customChecks.create(request.user!.id, projectId, { name: data.name, definition: data.definition as unknown as CustomCheckDefinition, severity: data.severity, ...(data.description !== undefined ? { description: data.description } : {}), ...(data.enabled !== undefined ? { enabled: data.enabled } : {}) }) }; }
  @Post('preview') async preview(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Body() body: unknown) { const parsed = definitionSchema.safeParse(body); if (!parsed.success) throw new BadRequestException('Invalid custom check definition.'); return this.customChecks.preview(request.user!.id, projectId, parsed.data as unknown as CustomCheckDefinition); }
  @Get(':checkId') async find(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('checkId') checkId: string) { const check = await this.customChecks.find(request.user!.id, projectId, checkId); if (!check) throw new BadRequestException('Custom check not found.'); return { check }; }
  @Patch(':checkId') async update(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('checkId') checkId: string, @Body() body: unknown) { const parsed = updateSchema.safeParse(body); if (!parsed.success) throw new BadRequestException('Invalid custom check update.'); const data = parsed.data; const input = { ...(data.name !== undefined ? { name: data.name } : {}), ...(data.description !== undefined ? { description: data.description } : {}), ...(data.enabled !== undefined ? { enabled: data.enabled } : {}), ...(data.severity !== undefined ? { severity: data.severity } : {}), ...(data.definition !== undefined ? { definition: data.definition as unknown as CustomCheckDefinition } : {}) } as UpdateCustomCheckRequest; const check = await this.customChecks.update(request.user!.id, projectId, checkId, input); if (!check) throw new BadRequestException('Custom check not found.'); return { check }; }
  @Delete(':checkId') async remove(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('checkId') checkId: string) { if (!(await this.customChecks.delete(request.user!.id, projectId, checkId))) throw new BadRequestException('Custom check not found.'); return { deleted: true }; }
}
