import { BadRequestException, Injectable, ServiceUnavailableException } from '@nestjs/common';
import type { CreateScanRequest, Project, Scan, ScanProgressResponse } from '@visionqa/contracts';
import { detectorCatalog } from '@visionqa/detectors';
import type { ScanJobDispatcher } from '@visionqa/queue';
import { BullMqScanJobDispatcher } from '@visionqa/queue';
import { FirebaseBrowserExecutionRepository, FirebaseCrawlPageRepository, FirebaseEvidenceRepository, FirebaseEvidenceStorage, FirebaseIssueRepository, FirebaseResourceRepository, FirebaseScanRepository } from '@visionqa/database/firebase';
import { ProjectsService } from '../projects/projects.service.js';
import { ScanOrchestrator } from './scans.orchestrator.js';
import type { BrowserFactQuery } from '@visionqa/database/contracts';

const defaults = { browsers: ['chromium'] as const, viewports: [{ width: 1440, height: 900 }] };

@Injectable()
export class ScansService {
  private readonly scans = new FirebaseScanRepository();
  private readonly crawlPages = new FirebaseCrawlPageRepository();
  private readonly resources = new FirebaseResourceRepository();
  private readonly issues = new FirebaseIssueRepository();
  private readonly browserExecutions = new FirebaseBrowserExecutionRepository();
  private readonly evidence = new FirebaseEvidenceRepository();
  private readonly evidenceStorage = new FirebaseEvidenceStorage();
  private readonly dispatcher: ScanJobDispatcher;
  private readonly orchestrator = new ScanOrchestrator();
  constructor(private readonly projects: ProjectsService) { this.dispatcher = new BullMqScanJobDispatcher(process.env.REDIS_URL ?? 'redis://127.0.0.1:6379'); }

  private async context(ownerId: string, projectId: string, environmentId: string): Promise<{ project: Project; targetUrl: string }> { const project = await this.projects.find(ownerId, projectId); if (!project) throw new BadRequestException('Project not found.'); const environment = project.environments.find((item) => item.id === environmentId); if (!environment) throw new BadRequestException('Environment does not belong to this project.'); return { project, targetUrl: environment.baseUrl }; }
  private normalize(input: CreateScanRequest, project: Project): CreateScanRequest & { checks: string[]; requestedUrls: string[]; browsers: Scan['browsers']; viewports: Scan['viewports']; options: Scan['options'] } { const modules = input.module === 'full-scan' ? input.modules ?? [] : undefined; if (input.module === 'full-scan' && !modules?.length) throw new BadRequestException('Select at least one module for a full scan.'); const checks = modules ? [...new Set(modules.flatMap((item) => item.checks))] : [...new Set(input.checks ?? [])]; if (!checks.length) throw new BadRequestException('Select at least one check.'); for (const check of checks) { const metadata = detectorCatalog.find((item) => item.id === check); const module = modules?.find((item) => item.checks.includes(check))?.module ?? input.module; if (!metadata || metadata.module !== module) throw new BadRequestException(`Check "${check}" is not supported by the selected module.`); } const requestedUrls = input.requestedUrls?.length ? input.requestedUrls : [project.baseUrl]; return { ...input, ...(modules ? { modules } : {}), checks, requestedUrls, browsers: input.browsers?.length ? input.browsers : [...defaults.browsers], viewports: input.viewports?.length ? input.viewports : defaults.viewports, options: input.options ?? {} }; }
  async create(ownerId: string, projectId: string, input: CreateScanRequest): Promise<Scan> { const { project } = await this.context(ownerId, projectId, input.environmentId); const normalized = this.normalize(input, project); const scan = await this.scans.create(ownerId, project, normalized); if (!scan) throw new BadRequestException('Project not found.'); try { await this.orchestrator.dispatch(scan, project, this.dispatcher); console.info(JSON.stringify({ event: 'scan_created', scanId: scan.id, projectId, module: scan.module })); return scan; } catch { await this.scans.updateStatus(ownerId, projectId, scan.id, 'failed', { failureCode: 'QUEUE_DISPATCH_FAILED', failureMessage: 'The scan could not be queued.' }); console.error(JSON.stringify({ event: 'queue_dispatch_failed', scanId: scan.id, projectId, module: scan.module })); throw new ServiceUnavailableException('The scan could not be queued. Please ensure the scan queue is available and try again.'); } }
  list(ownerId: string, projectId: string): Promise<Scan[] | null> { return this.scans.findByProject(ownerId, projectId); }
  get(ownerId: string, projectId: string, scanId: string): Promise<Scan | null> { return this.scans.findById(ownerId, projectId, scanId); }
  async progress(ownerId: string, projectId: string, scanId: string): Promise<ScanProgressResponse | null> { const scan = await this.get(ownerId, projectId, scanId); return scan ? { scanId, status: scan.status, progress: scan.progress } : null; }
  async cancel(ownerId: string, projectId: string, scanId: string): Promise<Scan | null> { const scan = await this.get(ownerId, projectId, scanId); if (!scan) return null; if (scan.status === 'completed' || scan.status === 'failed') throw new BadRequestException(`A ${scan.status} scan cannot be cancelled.`); if (scan.status === 'cancelled') return scan; const cancelled = await this.scans.updateStatus(ownerId, projectId, scanId, 'cancelled'); if (cancelled) console.info(JSON.stringify({ event: 'scan_cancelled', scanId, projectId, module: scan.module })); return cancelled; }
  pages(ownerId: string, projectId: string, scanId: string, options?: { status?: import('@visionqa/contracts').CrawlStatus; depth?: number; limit?: number; cursor?: string }) { return this.get(ownerId, projectId, scanId).then((scan) => scan ? this.crawlPages.findByScan(ownerId, projectId, scanId, options) : null); }
  summary(ownerId: string, projectId: string, scanId: string) { return this.get(ownerId, projectId, scanId).then((scan) => scan ? this.crawlPages.summary(ownerId, projectId, scanId) : null); }
  quality(ownerId: string, projectId: string, scanId: string, type: 'robots' | 'sitemap') { return this.get(ownerId, projectId, scanId).then((scan) => scan ? this.crawlPages.getQuality(ownerId, projectId, scanId, type) : null); }
  sitemapUrls(ownerId: string, projectId: string, scanId: string, limit = 100) { return this.get(ownerId, projectId, scanId).then((scan) => scan ? this.crawlPages.sitemapUrls(ownerId, projectId, scanId, limit) : null); }
  async comparison(ownerId: string, projectId: string, scanId: string) { const scan = await this.get(ownerId, projectId, scanId); if (!scan) return null; const [crawled, sitemap] = await Promise.all([this.crawlPages.allNormalizedUrls(ownerId, projectId, scanId), this.crawlPages.sitemapUrls(ownerId, projectId, scanId, 50000)]); const crawlSet = new Set(crawled); const sitemapSet = new Set(sitemap); return { matched: sitemap.filter((url) => crawlSet.has(url)), crawlOnly: crawled.filter((url) => !sitemapSet.has(url)), sitemapOnly: sitemap.filter((url) => !crawlSet.has(url)) }; }
  resourcesForScan(ownerId: string, projectId: string, scanId: string, options?: Parameters<FirebaseResourceRepository['findByScan']>[3]) { return this.get(ownerId, projectId, scanId).then((scan) => scan ? this.resources.findByScan(ownerId, projectId, scanId, options) : null); }
  issuesForProject(ownerId: string, projectId: string, options?: Parameters<FirebaseIssueRepository['findByProject']>[2]) { return this.issues.findByProject(ownerId, projectId, options); }
  issue(ownerId: string, projectId: string, issueId: string) { return this.issues.findById(ownerId, projectId, issueId); }
  updateIssueStatus(ownerId: string, projectId: string, issueId: string, status: import('@visionqa/contracts').IssueStatus) { return this.issues.updateStatus(ownerId, projectId, issueId, status); }
  browserPages(ownerId: string, projectId: string, scanId: string, options?: { limit?: number; cursor?: string }) { return this.get(ownerId, projectId, scanId).then((scan) => scan ? this.browserExecutions.findPages(ownerId, projectId, scanId, options) : null); }
  browserFacts(ownerId: string, projectId: string, scanId: string, kind: import('@visionqa/contracts').BrowserFact['kind'], options?: BrowserFactQuery) { return this.get(ownerId, projectId, scanId).then((scan) => scan ? this.browserExecutions.findFacts(ownerId, projectId, scanId, kind, options) : null); }
  async browserNetwork(ownerId: string, projectId: string, scanId: string, options?: BrowserFactQuery) { const scan = await this.get(ownerId, projectId, scanId); if (!scan) return null; const [responses, failures, blocked] = await Promise.all([this.browserExecutions.findFacts(ownerId, projectId, scanId, 'RESPONSE', options), this.browserExecutions.findFacts(ownerId, projectId, scanId, 'FAILED_REQUEST', options), this.browserExecutions.findFacts(ownerId, projectId, scanId, 'NETWORK_POLICY_BLOCKED', options)]); return { facts: [...responses.facts, ...failures.facts, ...blocked.facts].slice(0, Math.min(options?.limit ?? 100, 100)) }; }
  browserSummary(ownerId: string, projectId: string, scanId: string) { return this.get(ownerId, projectId, scanId).then((scan) => scan ? this.browserExecutions.summary(ownerId, projectId, scanId) : null); }
  browserResults(ownerId: string, projectId: string, scanId: string) { return Promise.all([this.browserPages(ownerId, projectId, scanId), this.browserSummary(ownerId, projectId, scanId)]).then(([pages, summary]) => pages && summary ? { ...pages, summary } : null); }
  async evidenceForScan(ownerId: string, projectId: string, scanId: string, options?: { limit?: number; cursor?: string }) { const scan = await this.get(ownerId, projectId, scanId); return scan ? this.evidence.findByScan(ownerId, projectId, scanId, options) : null; }
  async evidenceById(ownerId: string, projectId: string, evidenceId: string) { const record = await this.evidence.findById(ownerId, projectId, evidenceId); if (!record) return null; try { return { ...record, url: await this.evidenceStorage.getSignedReadUrl(record.storagePath) }; } catch { throw new ServiceUnavailableException('Evidence is temporarily unavailable.'); } }
}
