import { BadRequestException, Body, Controller, Get, Param, Patch, Post, Query, Req, UseGuards } from '@nestjs/common';
import { z } from 'zod';
import { qaModules, type CreateScanRequest, type CrawlStatus } from '@visionqa/contracts';
import { detectorCatalog } from '@visionqa/detectors';
import { FirebaseSessionGuard, type AuthenticatedRequest } from '../auth/firebase-session.guard.js';
import { ScansService } from './scans.service.js';

const scanSchema = z.object({ url: z.string().trim().url(), scope: z.enum(['single-page', 'start-url', 'path', 'site']).optional(), module: z.enum(qaModules), checks: z.array(z.string().min(1)).optional(), modules: z.array(z.object({ module: z.enum(qaModules).exclude(['full-scan']), checks: z.array(z.string().min(1)).min(1) })).optional(), browsers: z.array(z.enum(['chromium', 'firefox', 'webkit'])).optional(), viewports: z.array(z.object({ width: z.number().int().min(1).max(10000), height: z.number().int().min(1).max(10000), deviceScaleFactor: z.number().positive().optional() })).optional(), options: z.object({ maxPages: z.number().int().positive().max(1000).optional(), maxDepth: z.number().int().nonnegative().max(20).optional(), sameOriginOnly: z.boolean().optional(), includePatterns: z.array(z.string().max(200)).max(20).optional(), excludePatterns: z.array(z.string().max(200)).max(20).optional(), requestTimeoutMs: z.number().int().positive().max(60000).optional(), concurrency: z.number().int().positive().max(5).optional(), maxExternalLinks: z.number().int().positive().max(500).optional(), captureEvidence: z.boolean().optional() }).optional() });

@Controller('api/v1/projects/:projectId/scans')
@UseGuards(FirebaseSessionGuard)
export class ScansController {
  constructor(private readonly scans: ScansService) {}
  @Post() async create(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Body() body: unknown) { const parsed = scanSchema.safeParse(body); if (!parsed.success) throw new BadRequestException('Invalid scan request.'); return { scan: await this.scans.create(request.user!.id, projectId, parsed.data as CreateScanRequest) }; }
  @Get() async list(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string) { const scans = await this.scans.list(request.user!.id, projectId); if (!scans) throw new BadRequestException('Project not found.'); return { scans }; }
  @Get(':scanId') async get(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const scan = await this.scans.get(request.user!.id, projectId, scanId); if (!scan) throw new BadRequestException('Scan not found.'); return { scan }; }
  @Get(':scanId/progress') async progress(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const progress = await this.scans.progress(request.user!.id, projectId, scanId); if (!progress) throw new BadRequestException('Scan not found.'); return progress; }
  @Post(':scanId/cancel') async cancel(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const scan = await this.scans.cancel(request.user!.id, projectId, scanId); if (!scan) throw new BadRequestException('Scan not found.'); return { scan }; }
  @Get(':scanId/crawl/pages') async pages(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const status = query.status as CrawlStatus | undefined; const depth = query.depth ? Number(query.depth) : undefined; const limit = query.limit ? Number(query.limit) : undefined; const options = { ...(status ? { status } : {}), ...(depth !== undefined ? { depth } : {}), ...(limit !== undefined ? { limit } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }; const result = await this.scans.pages(request.user!.id, projectId, scanId, options); if (!result) throw new BadRequestException('Scan not found.'); return result; }
  @Get(':scanId/crawl/summary') async summary(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const result = await this.scans.summary(request.user!.id, projectId, scanId); if (!result) throw new BadRequestException('Scan not found.'); return result; }
  @Get(':scanId/crawl/robots') async robots(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const result = await this.scans.quality(request.user!.id, projectId, scanId, 'robots'); if (!result) throw new BadRequestException('Scan or robots result not found.'); return result; }
  @Get(':scanId/crawl/sitemap') async sitemap(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const result = await this.scans.quality(request.user!.id, projectId, scanId, 'sitemap'); if (!result) throw new BadRequestException('Scan or sitemap result not found.'); return result; }
  @Get(':scanId/crawl/sitemap/urls') async sitemapUrls(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query('limit') limit?: string) { const result = await this.scans.sitemapUrls(request.user!.id, projectId, scanId, limit ? Number(limit) : 100); if (!result) throw new BadRequestException('Scan not found.'); return { urls: result }; }
  @Get(':scanId/crawl/comparison') async comparison(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const result = await this.scans.comparison(request.user!.id, projectId, scanId); if (!result) throw new BadRequestException('Scan not found.'); return result; }
  @Get(':scanId/resources') async resources(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const result = await this.scans.resourcesForScan(request.user!.id, projectId, scanId, { ...(query.type ? { type: query.type as import('@visionqa/contracts').ResourceType } : {}), ...(query.status ? { status: query.status } : {}), ...(query.internal !== undefined ? { internal: query.internal === 'true' } : {}), ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); if (!result) throw new BadRequestException('Scan not found.'); return result; }
  @Get(':scanId/links') async links(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const result = await this.scans.resourcesForScan(request.user!.id, projectId, scanId, { type: 'LINK', ...(query.status ? { status: query.status } : {}), ...(query.internal !== undefined ? { internal: query.internal === 'true' } : {}), ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); if (!result) throw new BadRequestException('Scan not found.'); return result; }
  @Get(':scanId/browser/results') async browserResults(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const result = await this.scans.browserResults(request.user!.id, projectId, scanId); if (!result) throw new BadRequestException('Scan not found.'); return result; }
  @Get(':scanId/visual/summary') async visualSummary(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const result = await this.scans.visualSummary(request.user!.id, projectId, scanId); if (!result) throw new BadRequestException('Visual scan not found.'); return result; }
  @Get(':scanId/visual/findings') async visualFindings(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const result = await this.scans.visualFindings(request.user!.id, projectId, scanId, { ...(query.detectorId ? { detectorId: query.detectorId } : {}), ...(query.severity ? { severity: query.severity } : {}), ...(query.pageUrl ? { pageUrl: query.pageUrl } : {}), ...(query.status ? { status: query.status as import('@visionqa/contracts').IssueStatus } : {}), ...(query.viewport ? { viewport: query.viewport } : {}), ...(query.browser ? { browser: query.browser } : {}), ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); if (!result) throw new BadRequestException('Visual scan not found.'); return result; }
  @Get(':scanId/visual/pages') async visualPages(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const result = await this.scans.visualPages(request.user!.id, projectId, scanId, { ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); if (!result) throw new BadRequestException('Visual scan not found.'); return result; }
  @Get(':scanId/visual/evidence') async visualEvidence(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const type = query.type === 'VISUAL_ANNOTATION' || query.type === 'SCREENSHOT' ? query.type : undefined; const result = await this.scans.visualEvidence(request.user!.id, projectId, scanId, { ...(type ? { type } : {}), ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); if (!result) throw new BadRequestException('Visual scan not found.'); return result; }
  @Get(':scanId/accessibility/summary') async accessibilitySummary(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const result = await this.scans.accessibilitySummary(request.user!.id, projectId, scanId); if (!result) throw new BadRequestException('Accessibility scan not found.'); return result; }
  @Get(':scanId/accessibility/findings') async accessibilityFindings(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const result = await this.scans.accessibilityFindings(request.user!.id, projectId, scanId, { ...(query.detectorId ? { detectorId: query.detectorId } : {}), ...(query.severity ? { severity: query.severity } : {}), ...(query.pageUrl ? { pageUrl: query.pageUrl } : {}), ...(query.ruleId ? { ruleId: query.ruleId } : {}), ...(query.viewport ? { viewport: query.viewport } : {}), ...(query.browser ? { browser: query.browser } : {}), ...(query.status ? { status: query.status as import('@visionqa/contracts').IssueStatus } : {}), ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); if (!result) throw new BadRequestException('Accessibility scan not found.'); return result; }
  @Get(':scanId/seo/summary') async seoSummary(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const result = await this.scans.seoSummary(request.user!.id, projectId, scanId); if (!result) throw new BadRequestException('SEO scan not found.'); return result; }
  @Get(':scanId/seo/findings') async seoFindings(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const result = await this.scans.seoFindings(request.user!.id, projectId, scanId, { ...(query.detectorId ? { detectorId: query.detectorId } : {}), ...(query.severity ? { severity: query.severity } : {}), ...(query.pageUrl ? { pageUrl: query.pageUrl } : {}), ...(query.status ? { status: query.status as import('@visionqa/contracts').IssueStatus } : {}), ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); if (!result) throw new BadRequestException('SEO scan not found.'); return result; }
  @Get(':scanId/browser/pages') async browserPages(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const result = await this.scans.browserPages(request.user!.id, projectId, scanId, { ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); if (!result) throw new BadRequestException('Scan not found.'); return result; }
  @Get(':scanId/browser/console') async browserConsole(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const result = await this.scans.browserFacts(request.user!.id, projectId, scanId, 'CONSOLE', { ...(query.type ? { type: query.type } : {}), ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); if (!result) throw new BadRequestException('Scan not found.'); return result; }
  @Get(':scanId/browser/network') async browserNetwork(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const result = await this.scans.browserNetwork(request.user!.id, projectId, scanId, { ...(query.resourceType ? { resourceType: query.resourceType } : {}), ...(query.result ? { result: query.result as 'SUCCESS' | 'FAILED' | 'HTTP_ERROR' | 'BLOCKED_BY_POLICY' } : {}), ...(query.statusCode ? { statusCode: Number(query.statusCode) } : {}), ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); if (!result) throw new BadRequestException('Scan not found.'); return result; }
  @Get(':scanId/browser/summary') async browserSummary(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const result = await this.scans.browserSummary(request.user!.id, projectId, scanId); if (!result) throw new BadRequestException('Scan not found.'); return result; }
  @Get(':scanId/evidence') async scanEvidence(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const result = await this.scans.evidenceForScan(request.user!.id, projectId, scanId, { ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); if (!result) throw new BadRequestException('Scan not found.'); return result; }
  @Get(':scanId/performance/summary') async performanceSummary(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string) { const result = await this.scans.performanceSummary(request.user!.id, projectId, scanId); if (!result) throw new BadRequestException('Performance scan not found.'); return result; }
  @Get(':scanId/performance/pages') async performancePages(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('scanId') scanId: string, @Query() query: Record<string, string | undefined>) { const result = await this.scans.performancePages(request.user!.id, projectId, scanId, { ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); if (!result) throw new BadRequestException('Performance scan not found.'); return result; }
}

@Controller('api/v1/projects/:projectId/evidence')
@UseGuards(FirebaseSessionGuard)
export class EvidenceController {
  constructor(private readonly scans: ScansService) {}
  @Get(':evidenceId') async get(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('evidenceId') evidenceId: string) { const evidence = await this.scans.evidenceById(request.user!.id, projectId, evidenceId); if (!evidence) throw new BadRequestException('Evidence not found.'); return evidence; }
}

@Controller('api/v1/projects/:projectId/issues')
@UseGuards(FirebaseSessionGuard)
export class IssuesController {
  constructor(private readonly scans: ScansService) {}
  @Get() list(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Query() query: Record<string, string | undefined>) { return this.scans.issuesForProject(request.user!.id, projectId, { ...(query.severity ? { severity: query.severity } : {}), ...(query.status ? { status: query.status as import('@visionqa/contracts').IssueStatus } : {}), ...(query.module ? { module: query.module } : {}), ...(query.detectorId ? { detectorId: query.detectorId } : {}), ...(query.limit ? { limit: Number(query.limit) } : {}), ...(query.cursor ? { cursor: query.cursor } : {}) }); }
  @Get(':issueId') async get(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('issueId') issueId: string) { const issue = await this.scans.issue(request.user!.id, projectId, issueId); if (!issue) throw new BadRequestException('Issue not found.'); return { issue }; }
  @Patch(':issueId/status') async status(@Req() request: AuthenticatedRequest, @Param('projectId') projectId: string, @Param('issueId') issueId: string, @Body() body: { status?: string }) { const parsed = z.object({ status: z.enum(['OPEN', 'CONFIRMED', 'FALSE_POSITIVE', 'IGNORED', 'FIXED', 'REOPENED']) }).safeParse(body); if (!parsed.success) throw new BadRequestException('Invalid issue status.'); const issue = await this.scans.updateIssueStatus(request.user!.id, projectId, issueId, parsed.data.status); if (!issue) throw new BadRequestException('Issue not found.'); return { issue }; }
}

@Controller('api/v1/detectors')
export class DetectorsController {
  @Get() list() { return { detectors: detectorCatalog }; }
}
