import type { Project, Scan } from '@visionqa/contracts';
import { detectorCatalog } from '@visionqa/detectors';
import type { BrowserScanJob, CrawlJob, HttpScanJob, QueueCapability, ScanExecutionPlan, ScanJobDispatcher } from '@visionqa/queue';

const capabilityFor = (check: string): QueueCapability => detectorCatalog.find((item) => item.id === check)?.requirements.crawl ? 'crawl' : detectorCatalog.find((item) => item.id === check)?.requirements.browser ? 'browser' : 'http';
export class ScanOrchestrator {
  buildPlan(scan: Scan): ScanExecutionPlan { const capabilities = new Map<QueueCapability, string[]>(); for (const check of scan.checks) { const capability = capabilityFor(check); capabilities.set(capability, [...(capabilities.get(capability) ?? []), check]); } return { scanId: scan.id, tasks: [...capabilities.entries()].map(([capability, checks]) => ({ capability, checks })) }; }
  async dispatch(scan: Scan, project: Project, dispatcher: ScanJobDispatcher): Promise<void> { const targetUrl = project.environments.find((environment) => environment.id === scan.environmentId)?.baseUrl ?? project.baseUrl; for (const task of this.buildPlan(scan).tasks) { if (task.capability === 'crawl') await dispatcher.dispatchCrawl({ scanId: scan.id, projectId: scan.projectId, environmentId: scan.environmentId, targetUrl, checks: task.checks, options: scan.options, capability: 'crawl' } satisfies CrawlJob); if (task.capability === 'http') await dispatcher.dispatchHttp({ scanId: scan.id, projectId: scan.projectId, environmentId: scan.environmentId, targetUrl, checks: task.checks, options: scan.options, capability: 'http' } satisfies HttpScanJob); if (task.capability === 'browser') await dispatcher.dispatchBrowser({ scanId: scan.id, projectId: scan.projectId, environmentId: scan.environmentId, targetUrl, checks: task.checks, options: scan.options, capability: 'browser', module: scan.module, browsers: scan.browsers, viewports: scan.viewports } satisfies BrowserScanJob); } }
}
