'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { CreateProjectRequest } from '@visionqa/contracts';
import { createProject } from '@/features/projects/project.service';
import { environmentTypes, validateProjectInput } from '@/features/projects/project.validation';
import { useProjects } from '@/features/projects/project-context';

function EnvironmentSelect({ value, onChange }: { value: CreateProjectRequest['environmentType']; onChange: (value: CreateProjectRequest['environmentType']) => void }) {
  const [open, setOpen] = useState(false);
  return <div className="relative mt-2"><button type="button" className="liquid-control flex h-12 w-full items-center justify-between rounded-xl px-4 text-left text-[#32133f] outline-none" aria-expanded={open} aria-haspopup="listbox" onClick={() => setOpen((current) => !current)}><span className="font-semibold">{value}</span><span className={`text-[#ad08d1] transition-transform ${open ? 'rotate-180' : ''}`}>⌄</span></button>{open && <div className="liquid-dropdown absolute left-0 right-0 z-20 mt-2 overflow-hidden rounded-xl p-1" role="listbox" aria-label="Environment type">{environmentTypes.map((type) => <button className={`liquid-dropdown-option ${type === value ? 'liquid-dropdown-option-selected' : ''}`} key={type} type="button" role="option" aria-selected={type === value} onClick={() => { onChange(type); setOpen(false); }}>{type}<span>{type === value ? '✓' : ''}</span></button>)}</div>}</div>;
}

export default function NewProjectPage() { const router = useRouter(); const { refreshProjects } = useProjects(); const [form, setForm] = useState<CreateProjectRequest>({ name: '', baseUrl: '', environmentName: 'Production', environmentType: 'production' }); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const update = (key: keyof CreateProjectRequest, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); const validation = validateProjectInput(form); if (validation) { setError(validation); return; } setSaving(true); setError(null); try { await createProject(form); await refreshProjects(); router.replace('/dashboard'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create project.'); } finally { setSaving(false); } }
  return <section className="max-w-2xl"><p className="text-xs font-bold tracking-[0.2em] text-[#ad08d1]">NEW PROJECT</p><h1 className="mt-3 text-3xl font-bold text-[#32133f]">Create a project</h1><p className="mt-3 text-[#76527f]">Projects keep your website, environments, and future QA runs together.</p><form className="mt-8 space-y-5 rounded-2xl border border-fuchsia-200/70 bg-white/55 p-6" onSubmit={submit}>{error && <p className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<label className="block text-sm font-semibold text-[#542064]">Project name<input className="liquid-control mt-2 block w-full rounded-xl px-4 py-3 text-[#32133f] outline-none" value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="Acme website" /></label><label className="block text-sm font-semibold text-[#542064]">Website URL<input className="liquid-control mt-2 block w-full rounded-xl px-4 py-3 text-[#32133f] outline-none" value={form.baseUrl} onChange={(event) => update('baseUrl', event.target.value)} placeholder="https://example.com" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-semibold text-[#542064]">Environment name<input className="liquid-control mt-2 block w-full rounded-xl px-4 py-3 text-[#32133f] outline-none" value={form.environmentName} onChange={(event) => update('environmentName', event.target.value)} /></label><label className="block text-sm font-semibold text-[#542064]">Environment type<EnvironmentSelect value={form.environmentType} onChange={(value) => update('environmentType', value)} /></label></div><button className="liquid-primary rounded-xl px-6 py-3 font-semibold text-white disabled:opacity-60" disabled={saving} type="submit">{saving ? 'Creating…' : 'Create project'}</button></form></section>; }
