'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { CreateProjectRequest } from '@visionqa/contracts';
import { createProject } from '@/features/projects/project.service';
import { useProjects } from '@/features/projects/project-context';

export default function NewProjectPage() { const router = useRouter(); const { refreshProjects } = useProjects(); const [name, setName] = useState(''); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); async function submit(event: React.FormEvent) { event.preventDefault(); if (!name.trim()) { setError('Enter a project name.'); return; } setSaving(true); setError(null); try { await createProject({ name: name.trim() } satisfies CreateProjectRequest); await refreshProjects(); router.replace('/dashboard'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create project.'); } finally { setSaving(false); } } return <section className="max-w-2xl"><p className="text-xs font-bold tracking-[0.2em] text-[#ad08d1]">NEW PROJECT</p><h1 className="mt-3 text-3xl font-bold text-[#32133f]">Create a project</h1><p className="mt-3 text-[#76527f]">Projects are workspaces. Choose the URL independently each time you run a QA check.</p><form className="mt-8 space-y-5 rounded-2xl border border-fuchsia-200/70 bg-white/55 p-6" onSubmit={submit}>{error && <p className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{error}</p>}<label className="block text-sm font-semibold text-[#542064]">Project name<input required className="liquid-control mt-2 block w-full rounded-xl px-4 py-3 text-[#32133f] outline-none" value={name} onChange={(event) => setName(event.target.value)} placeholder="Dewalt QA" /></label><button className="liquid-primary rounded-xl px-6 py-3 font-semibold text-white disabled:opacity-60" disabled={saving} type="submit">{saving ? 'Creating…' : 'Create project'}</button></form></section>; }
