import { XMLParser } from 'fast-xml-parser';

export type RobotsGroup = { agents: string[]; rules: Array<{ type: 'allow' | 'disallow'; path: string }> };
export type RobotsResult = { parseStatus: 'PARSED' | 'MISSING' | 'WARNING' | 'ERROR'; rulesCount: number; sitemaps: string[]; groups: RobotsGroup[]; warnings: string[] };
export function parseRobots(body: string): RobotsResult { const groups: RobotsGroup[] = []; const sitemaps: string[] = []; const warnings: string[] = []; let current: RobotsGroup | null = null; for (const raw of body.slice(0, 512 * 1024).split(/\r?\n/)) { const line = raw.split('#', 1)[0]!.trim(); if (!line) continue; const separator = line.indexOf(':'); if (separator < 1) { warnings.push('Ignored malformed directive.'); continue; } const key = line.slice(0, separator).trim().toLowerCase(); const value = line.slice(separator + 1).trim(); if (key === 'user-agent') { if (!current || current.rules.length) { current = { agents: [], rules: [] }; groups.push(current); } current.agents.push(value.toLowerCase()); } else if (key === 'allow' || key === 'disallow') { if (!current) { warnings.push('Rule appeared before a user-agent.'); continue; } current.rules.push({ type: key, path: value }); } else if (key === 'sitemap' && value) sitemaps.push(value); } return { parseStatus: warnings.length ? 'WARNING' : 'PARSED', rulesCount: groups.reduce((count, group) => count + group.rules.length, 0), sitemaps: [...new Set(sitemaps)], groups, warnings }; }
export class RobotsPolicy { constructor(private readonly result: RobotsResult, private readonly agent = 'visionqa-crawler') {} isAllowed(url: string): boolean { const parsed = new URL(url); const path = parsed.pathname + parsed.search; const specific = this.result.groups.filter((group) => group.agents.includes(this.agent)); const wildcard = this.result.groups.filter((group) => group.agents.includes('*')); const rules = [...specific.flatMap((group) => group.rules).map((rule) => ({ ...rule, specificity: 1 })), ...wildcard.flatMap((group) => group.rules).map((rule) => ({ ...rule, specificity: 0 }))].filter((rule) => rule.path && path.startsWith(rule.path)).sort((a, b) => b.path.length - a.path.length || b.specificity - a.specificity || (a.type === 'allow' ? -1 : 1)); return rules[0]?.type !== 'disallow'; } }
export type SitemapEntry = { pageUrl: string; normalizedUrl: string; lastmod?: string; changefreq?: string; priority?: number; sourceSitemap: string };
const array = <T>(value: T | T[] | undefined): T[] => value === undefined ? [] : Array.isArray(value) ? value : [value];
export function parseSitemap(xml: string, sourceSitemap: string): { kind: 'urlset' | 'sitemapindex'; entries: SitemapEntry[]; children: string[] } { const parsed = new XMLParser({ processEntities: false, htmlEntities: false, ignoreAttributes: true, isArray: (name) => name === 'url' || name === 'sitemap' }); const root = parsed.parse(xml); if (root.urlset) { const entries = array(root.urlset.url).flatMap((item: Record<string, unknown>) => { const loc = typeof item.loc === 'string' ? item.loc.trim() : ''; if (!loc) return []; try { const url = new URL(loc); url.hash = ''; return [{ pageUrl: loc, normalizedUrl: url.toString(), ...(typeof item.lastmod === 'string' ? { lastmod: item.lastmod } : {}), ...(typeof item.changefreq === 'string' ? { changefreq: item.changefreq } : {}), ...(typeof item.priority === 'number' ? { priority: item.priority } : {}), sourceSitemap }]; } catch { return []; } }); return { kind: 'urlset', entries, children: [] }; } if (root.sitemapindex) { const children = array(root.sitemapindex.sitemap).flatMap((item: Record<string, unknown>) => typeof item.loc === 'string' && item.loc.trim() ? [item.loc.trim()] : []); return { kind: 'sitemapindex', entries: [], children }; } throw new Error('Unsupported sitemap XML.'); }
export type ComparisonType = 'MATCHED' | 'CRAWL_ONLY' | 'SITEMAP_ONLY' | 'ORPHAN_CANDIDATE';
export function compareUrls(crawled: string[], sitemap: string[]): Record<ComparisonType, string[]> { const crawl = new Set(crawled); const map = new Set(sitemap); const matched = [...map].filter((url) => crawl.has(url)); const sitemapOnly = [...map].filter((url) => !crawl.has(url)); const crawlOnly = [...crawl].filter((url) => !map.has(url)); return { MATCHED: matched, CRAWL_ONLY: crawlOnly, SITEMAP_ONLY: sitemapOnly, ORPHAN_CANDIDATE: sitemapOnly }; }
