import { parse } from 'node-html-parser';
import { Worker, type Job } from 'bullmq';
import type { CrawlJob } from '@visionqa/queue';
import { queueNames } from '@visionqa/queue';
import { FirebaseCrawlPageRepository, FirebaseResourceRepository, FirebaseScanRepository } from '@visionqa/database/firebase';
import type { ResourceType, ResourceReference } from '@visionqa/contracts';
import { OutboundNetworkPolicy } from '@visionqa/network-policy';
import { CrawlFrontier } from './CrawlFrontier.js';
import { crawlFailure, SecureHttpExecutor } from './SecureHttpExecutor.js';
import { parseRobots, parseSitemap, RobotsPolicy, type RobotsResult } from './CrawlQuality.js';

const hard = { maxPages: 1000, maxDepth: 20, timeoutMs: 60000, maxBytes: 5 * 1024 * 1024 };
export function normalizeUrl(raw: string): string { const url = new URL(raw); url.hash = ''; if ((url.protocol === 'http:' && url.port === '80') || (url.protocol === 'https:' && url.port === '443')) url.port = ''; return url.toString(); }
function matches(url: string, include: string[] = [], exclude: string[] = []): boolean { return !exclude.some((pattern) => url.includes(pattern)) && (!include.length || include.some((pattern) => url.includes(pattern))); }

export class CrawlJobProcessor {
  private readonly scans = new FirebaseScanRepository();
  private readonly pages = new FirebaseCrawlPageRepository();
  private readonly resources = new FirebaseResourceRepository();
  async start(): Promise<void> { const redisUrl = process.env.REDIS_URL ?? 'redis://127.0.0.1:6379'; new Worker<CrawlJob>(queueNames.crawl, (job) => this.process(job), { connection: { url: redisUrl }, concurrency: Number(process.env.CRAWL_CONCURRENCY ?? 3) }); console.log('VisionQA crawl worker ready'); }
  validate(job: CrawlJob): void { if (job.capability !== 'crawl' || !job.scanId || !job.projectId) throw new Error('Invalid crawl job.'); }
  private async runRobots(job: CrawlJob, executor: SecureHttpExecutor): Promise<RobotsResult> { const robotsUrl = `${new URL(job.targetUrl).origin}/robots.txt`; try { const response = await executor.get(robotsUrl); const parsed: RobotsResult = response.statusCode === 404 ? { parseStatus: 'MISSING', rulesCount: 0, sitemaps: [], groups: [], warnings: [] } : response.body ? parseRobots(response.body) : { parseStatus: 'ERROR', rulesCount: 0, sitemaps: [], groups: [], warnings: [] }; await this.pages.saveQuality(job.projectId, job.scanId, 'robots', { url: robotsUrl, finalUrl: response.url, statusCode: response.statusCode, contentType: response.contentType, rawSize: response.body.length, ...parsed }); return parsed; } catch (error) { const failure = crawlFailure(error); const parsed: RobotsResult = { parseStatus: 'ERROR', rulesCount: 0, sitemaps: [], groups: [], warnings: [failure.message] }; await this.pages.saveQuality(job.projectId, job.scanId, 'robots', { url: robotsUrl, ...parsed, errorCode: failure.code, errorMessage: failure.message }); return parsed; } }
  private async runSitemap(job: CrawlJob, executor: SecureHttpExecutor, declared: string[]): Promise<string[]> { const target = new URL(job.targetUrl); const pending = [...new Set(declared.length ? declared : [`${target.origin}/sitemap.xml`])]; const urls: string[] = []; const visited = new Set<string>(); while (pending.length && visited.size < 50 && urls.length < 50000) { if (await this.scans.isCancellationRequested(job.scanId)) return urls; const sitemapUrl = pending.shift()!; if (visited.has(sitemapUrl)) continue; visited.add(sitemapUrl); try { const response = await executor.get(sitemapUrl); if (!response.body || !['application/xml', 'text/xml', 'application/xhtml+xml'].includes(response.contentType)) continue; const parsed = parseSitemap(response.body, response.url); if (parsed.kind === 'sitemapindex') pending.push(...parsed.children.filter((child) => child.startsWith(target.origin))); else urls.push(...parsed.entries.map((entry) => entry.normalizedUrl).slice(0, 50000 - urls.length)); } catch { /* Sitemap failures are non-fatal. */ } } const unique = [...new Set(urls)]; await this.pages.saveQuality(job.projectId, job.scanId, 'sitemap', { sitemapUrls: [...visited], urlCount: unique.length }); await this.pages.saveSitemapEntries(job.projectId, job.scanId, unique); return unique; }
  async process(job: Job<CrawlJob>): Promise<void> {
    this.validate(job.data); const scan = await this.scans.findByIdForWorker(job.data.scanId); const targetUrl = scan?.target?.normalizedUrl; if (!targetUrl) throw new Error('Scan has no persisted target URL.'); const scanJob = { ...job.data, targetUrl }; const started = Date.now(); const options = job.data.options ?? {}; const selected = new Set(job.data.checks); const executor = new SecureHttpExecutor({ policy: new OutboundNetworkPolicy(), timeoutMs: Math.min(options.requestTimeoutMs ?? 15000, hard.timeoutMs), maxBytes: hard.maxBytes }); await this.scans.markStarted(job.data.scanId);
    const robotsResult = selected.has('robots') ? await this.runRobots(scanJob, executor) : null; const robotsPolicy = robotsResult ? new RobotsPolicy(robotsResult) : null; const sitemapUrls = selected.has('sitemap') ? await this.runSitemap(scanJob, executor, robotsResult?.sitemaps ?? []) : [];
    if (!selected.has('crawl')) { await this.scans.complete(job.data.scanId, { pagesDiscovered: 0, pagesFetched: 0, pagesFailed: 0, pagesSkipped: 0, sitemapUrls: sitemapUrls.length, durationMs: Date.now() - started }); return; }
    const maxPages = Math.min(options.maxPages ?? 100, hard.maxPages); const maxDepth = Math.min(options.maxDepth ?? 3, hard.maxDepth); const sameOriginOnly = options.sameOriginOnly ?? true; const root = normalizeUrl(targetUrl); const origin = new URL(root).origin; const frontier = new CrawlFrontier(maxPages, maxDepth); frontier.add({ url: root, normalizedUrl: root, depth: 0 }); let processed = 0; let failed = 0; let skipped = 0; let maxDepthReached = 0; const abort = new AbortController();
    try {
      while (frontier.size) {
        if (await this.scans.isCancellationRequested(job.data.scanId)) { abort.abort(); return; } const item = frontier.next()!; maxDepthReached = Math.max(maxDepthReached, item.depth); const page = await this.pages.createDiscovered({ scanId: job.data.scanId, projectId: job.data.projectId, url: item.url, normalizedUrl: item.normalizedUrl, depth: item.depth, ...(item.sourceUrl ? { sourceUrl: item.sourceUrl } : {}), redirectChain: [] });
        if (robotsPolicy && !robotsPolicy.isAllowed(item.url)) { skipped++; await this.pages.markSkipped(job.data.scanId, item.normalizedUrl, 'Blocked by robots.txt'); await this.scans.updateProgress(job.data.scanId, { completed: processed, total: frontier.discovered, percent: 0, discovered: frontier.discovered, processed, pending: frontier.size, failed }); continue; }
        try {
          const began = Date.now(); const response = await executor.get(item.url, abort.signal); if (!response.body || !['text/html', 'application/xhtml+xml'].includes(response.contentType)) { skipped++; await this.pages.markSkipped(job.data.scanId, item.normalizedUrl, `Unsupported content type: ${response.contentType || 'unknown'}`); } else { const document = parse(response.body); const extracted: Array<Omit<ResourceReference, 'id' | 'discoveredAt'>> = []; const add = (target: string | undefined, resourceType: ResourceType, relationship: string) => { if (!target || /^(mailto|tel|javascript|data|blob):/i.test(target)) return; try { const absolute = new URL(target, response.url); extracted.push({ scanId: job.data.scanId, projectId: job.data.projectId, sourcePageId: page.id, sourceUrl: item.url, targetUrl: absolute.toString(), normalizedTargetUrl: normalizeUrl(absolute.toString()), resourceType, relationship, isInternal: absolute.origin === origin, redirectChain: [] }); } catch { /* Invalid resource URLs are ignored. */ } }; document.querySelectorAll('a[href]').forEach((node) => add(node.getAttribute('href'), 'LINK', 'href')); document.querySelectorAll('img[src]').forEach((node) => add(node.getAttribute('src'), 'IMAGE', 'src')); document.querySelectorAll('script[src]').forEach((node) => add(node.getAttribute('src'), 'SCRIPT', 'src')); document.querySelectorAll('link[rel="stylesheet"][href]').forEach((node) => add(node.getAttribute('href'), 'STYLESHEET', 'href')); document.querySelectorAll('video[src],audio[src],source[src]').forEach((node) => add(node.getAttribute('src'), 'MEDIA', 'src')); if (extracted.length) await this.resources.createMany(extracted); const title = document.querySelector('title')?.text.replace(/\s+/g, ' ').trim().slice(0, 500); await this.pages.markFetched(job.data.scanId, item.normalizedUrl, { statusCode: response.statusCode, contentType: response.contentType, ...(title ? { title } : {}), durationMs: Date.now() - began, redirectChain: response.redirectChain }); if (item.depth < maxDepth) { const base = document.querySelector('base')?.getAttribute('href'); let baseUrl = response.url; try { if (base) baseUrl = new URL(base, response.url).toString(); } catch { /* Invalid base URL is ignored. */ } for (const link of document.querySelectorAll('a[href]')) { const href = link.getAttribute('href'); if (!href || href.startsWith('#') || /^(mailto|tel|javascript|data|blob):/i.test(href)) continue; try { const discovered = new URL(href, baseUrl); if (sameOriginOnly && discovered.origin !== origin) continue; const normalized = normalizeUrl(discovered.toString()); if (matches(normalized, options.includePatterns, options.excludePatterns)) frontier.add({ url: discovered.toString(), normalizedUrl: normalized, depth: item.depth + 1, sourceUrl: item.url }); } catch { /* Malformed links are ignored. */ } } } } processed++;
        } catch (error) { const failure = crawlFailure(error); if (failure.code === 'CANCELLED') return; failed++; await this.pages.markFailed(job.data.scanId, item.normalizedUrl, failure.code, failure.message); }
        await this.scans.updateProgress(job.data.scanId, { completed: processed, total: frontier.discovered, percent: 0, discovered: frontier.discovered, processed, pending: frontier.size, failed });
      }
      await this.scans.complete(job.data.scanId, { pagesDiscovered: frontier.discovered, pagesFetched: processed - failed, pagesFailed: failed, pagesSkipped: skipped, maxDepthReached, sitemapUrls: sitemapUrls.length, durationMs: Date.now() - started });
    } catch (error) { const failure = crawlFailure(error); await this.scans.fail(job.data.scanId, failure.code, failure.message); throw error; }
  }
}
