import { request as httpRequest } from 'node:http';
import { request as httpsRequest } from 'node:https';
import { OutboundNetworkPolicy, NetworkPolicyError } from '@visionqa/network-policy';
import type { IncomingMessage } from 'node:http';

export type SecureHttpResponse = { url: string; statusCode: number; contentType: string; body: string; redirectChain: string[] };
export class CrawlHttpError extends Error { constructor(public readonly code: string, message: string) { super(message); this.name = 'CrawlHttpError'; } }
export type SecureHttpExecutorOptions = { policy?: OutboundNetworkPolicy; timeoutMs?: number; maxBytes?: number; maxRedirects?: number; userAgent?: string; acceptedContentTypes?: string[] };
export class SecureHttpExecutor {
  private readonly policy: OutboundNetworkPolicy;
  private readonly options: Required<Omit<SecureHttpExecutorOptions, 'policy'>>;
  constructor(options: SecureHttpExecutorOptions = {}) { this.policy = options.policy ?? new OutboundNetworkPolicy(); this.options = { timeoutMs: options.timeoutMs ?? 15000, maxBytes: options.maxBytes ?? 5 * 1024 * 1024, maxRedirects: options.maxRedirects ?? 5, userAgent: options.userAgent ?? 'VisionQA-Crawler/0.1', acceptedContentTypes: options.acceptedContentTypes ?? ['text/html', 'application/xhtml+xml', 'application/xml', 'text/xml', 'text/plain'] }; }
  async get(rawUrl: string, signal?: AbortSignal): Promise<SecureHttpResponse> { let current = rawUrl; const chain: string[] = []; for (let redirects = 0; redirects <= this.options.maxRedirects; redirects++) { const resolved = await this.policy.validateAndResolve(current); const response = await this.request(resolved.url, resolved.addresses[0]!, signal); const location = response.headers.location; if (location && [301, 302, 303, 307, 308].includes(response.statusCode)) { if (redirects === this.options.maxRedirects) throw new CrawlHttpError('TOO_MANY_REDIRECTS', 'Too many redirects'); const next = new URL(location, resolved.url).toString(); if (chain.includes(next) || next === current) throw new CrawlHttpError('REDIRECT_LOOP', 'Redirect loop detected'); chain.push(current); current = next; continue; } const contentType = String(response.headers['content-type'] ?? '').split(';', 1)[0]!.trim().toLowerCase(); if (!this.options.acceptedContentTypes.includes(contentType)) return { url: current, statusCode: response.statusCode, contentType, body: '', redirectChain: chain }; return { url: current, statusCode: response.statusCode, contentType, body: response.body, redirectChain: chain }; } throw new CrawlHttpError('TOO_MANY_REDIRECTS', 'Too many redirects'); }
  private request(url: URL, address: string, signal?: AbortSignal): Promise<{ statusCode: number; headers: IncomingMessage['headers']; body: string }> { return new Promise((resolve, reject) => { if (signal?.aborted) return reject(new CrawlHttpError('CANCELLED', 'Request cancelled')); const requester = url.protocol === 'https:' ? httpsRequest : httpRequest; const request = requester({ protocol: url.protocol, hostname: address, port: url.port || undefined, path: `${url.pathname}${url.search}`, headers: { host: url.host, 'user-agent': this.options.userAgent, accept: 'text/html,application/xhtml+xml' }, servername: url.hostname, lookup: (_hostname, _options, callback) => callback(null, address, address.includes(':') ? 6 : 4), timeout: this.options.timeoutMs }, (response) => this.readResponse(response, resolve, reject)); const abort = () => { request.destroy(); reject(new CrawlHttpError('CANCELLED', 'Request cancelled')); }; signal?.addEventListener('abort', abort, { once: true }); request.on('timeout', () => { request.destroy(); reject(new CrawlHttpError('TIMEOUT', 'Request timed out')); }); request.on('error', (error) => reject(signal?.aborted ? new CrawlHttpError('CANCELLED', 'Request cancelled') : new CrawlHttpError('CONNECTION_FAILED', error.message))); request.end(); }); }
  private readResponse(response: IncomingMessage, resolve: (value: { statusCode: number; headers: IncomingMessage['headers']; body: string }) => void, reject: (reason: Error) => void): void { const chunks: Buffer[] = []; let size = 0; response.on('data', (chunk: Buffer) => { size += chunk.length; if (size > this.options.maxBytes) { response.destroy(); reject(new CrawlHttpError('RESPONSE_TOO_LARGE', 'Response exceeds the configured limit')); } else chunks.push(chunk); }); response.on('end', () => resolve({ statusCode: response.statusCode ?? 0, headers: response.headers, body: Buffer.concat(chunks).toString('utf8') })); response.on('error', (error) => reject(new CrawlHttpError('CONNECTION_FAILED', error.message))); }
}
export function crawlFailure(error: unknown): { code: string; message: string } { if (error instanceof NetworkPolicyError) return { code: 'NETWORK_POLICY_BLOCKED', message: error.message }; if (error instanceof CrawlHttpError) return { code: error.code, message: error.message }; return { code: 'CONNECTION_FAILED', message: 'The page could not be fetched.' }; }
