import { FieldValue, type Timestamp } from 'firebase-admin/firestore';
import type { Evidence, EvidenceType } from '@visionqa/contracts';
import type { EvidenceRepository } from '../../contracts/storage.js';
import { getFirestoreDb } from '../firebase-admin.js';

const iso = (value: unknown): string | undefined => value && typeof (value as Timestamp).toDate === 'function' ? (value as Timestamp).toDate().toISOString() : typeof value === 'string' ? value : undefined;
const map = (id: string, data: Record<string, unknown>): Evidence => ({ id, projectId: String(data.projectId), ...(typeof data.scanId === 'string' ? { scanId: data.scanId } : {}), ...(typeof data.executionId === 'string' ? { executionId: data.executionId } : {}), type: String(data.type) as EvidenceType, storagePath: String(data.storagePath), contentType: String(data.contentType), sizeBytes: Number(data.sizeBytes ?? 0), ...(typeof data.browser === 'string' ? { browser: data.browser as NonNullable<Evidence['browser']> } : {}), ...(data.viewport && typeof data.viewport === 'object' ? { viewport: data.viewport as NonNullable<Evidence['viewport']> } : {}), ...(typeof data.pageUrl === 'string' ? { pageUrl: data.pageUrl } : {}), createdAt: iso(data.createdAt) ?? new Date(0).toISOString(), ...(data.metadata && typeof data.metadata === 'object' ? { metadata: data.metadata as NonNullable<Evidence['metadata']> } : {}) });

export class FirebaseEvidenceRepository implements EvidenceRepository {
  private collection(projectId: string) { return getFirestoreDb().collection('projects').doc(projectId).collection('evidence'); }
  async create(input: Omit<Evidence, 'id' | 'createdAt'>): Promise<Evidence> { const ref = this.collection(input.projectId).doc(); await ref.set({ ...input, id: ref.id, createdAt: FieldValue.serverTimestamp() }); return map(ref.id, (await ref.get()).data()!); }
  async findById(ownerId: string, projectId: string, evidenceId: string): Promise<Evidence | null> { const project = await getFirestoreDb().collection('projects').doc(projectId).get(); if (!project.exists || project.data()?.createdBy !== ownerId) return null; const doc = await this.collection(projectId).doc(evidenceId).get(); return doc.exists ? map(doc.id, doc.data()!) : null; }
  async findByScan(ownerId: string, projectId: string, scanId: string, options: { type?: EvidenceType; limit?: number; cursor?: string } = {}) { const project = await getFirestoreDb().collection('projects').doc(projectId).get(); if (!project.exists || project.data()?.createdBy !== ownerId) return { evidence: [] }; const limit = Math.min(options.limit ?? 50, 100); let query = this.collection(projectId).where('scanId', '==', scanId).orderBy('createdAt', 'desc').limit(limit) as FirebaseFirestore.Query; if (options.cursor) { const cursor = await this.collection(projectId).doc(options.cursor).get(); if (cursor.exists) query = query.startAfter(cursor); } const snapshot = await query.get(); const evidence = snapshot.docs.map((doc) => map(doc.id, doc.data())).filter((item) => !options.type || item.type === options.type); return { evidence, ...(snapshot.size === limit && snapshot.docs.at(-1) ? { nextCursor: snapshot.docs.at(-1)!.id } : {}) }; }
}
