import { FieldValue } from 'firebase-admin/firestore';
import { randomUUID } from 'node:crypto';
import { getFirestoreDb } from '../firebase-admin.js';
import type { CreateEnvironmentInput, Environment, EnvironmentRepository, UpdateEnvironmentInput } from '../../contracts/index.js';

function mapEnvironment(id: string, projectId: string, data: Record<string, unknown>): Environment { return { id, projectId, name: String(data.name ?? ''), type: String(data.type ?? 'custom') as Environment['type'], baseUrl: String(data.baseUrl ?? ''), isDefault: Boolean(data.isDefault) }; }

export class FirebaseEnvironmentRepository implements EnvironmentRepository {
  private project(projectId: string) { return getFirestoreDb().collection('projects').doc(projectId); }
  private async ownerProject(ownerId: string, projectId: string) { const snapshot = await this.project(projectId).get(); return snapshot.exists && snapshot.data()?.createdBy === ownerId ? snapshot : null; }
  async create(ownerId: string, projectId: string, input: CreateEnvironmentInput): Promise<Environment | null> { if (!(await this.ownerProject(ownerId, projectId))) return null; const ref = this.project(projectId).collection('environments').doc(randomUUID()); const parent = ref.parent; const makeDefault = await getFirestoreDb().runTransaction(async (transaction) => { const environments = await transaction.get(parent); const shouldDefault = input.isDefault === true || environments.empty; if (input.isDefault === true) environments.docs.forEach((doc) => transaction.update(doc.ref, { isDefault: false, updatedAt: FieldValue.serverTimestamp() })); transaction.set(ref, { id: ref.id, projectId, ...input, isDefault: shouldDefault, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); return shouldDefault; }); void makeDefault; const created = await ref.get(); return mapEnvironment(ref.id, projectId, created.data()!); }
  async findByProject(ownerId: string, projectId: string): Promise<Environment[] | null> { if (!(await this.ownerProject(ownerId, projectId))) return null; const snapshot = await this.project(projectId).collection('environments').get(); return snapshot.docs.map((doc) => mapEnvironment(doc.id, projectId, doc.data())); }
  async findById(ownerId: string, projectId: string, environmentId: string): Promise<Environment | null> { if (!(await this.ownerProject(ownerId, projectId))) return null; const doc = await this.project(projectId).collection('environments').doc(environmentId).get(); return doc.exists ? mapEnvironment(environmentId, projectId, doc.data()!) : null; }
  async update(ownerId: string, projectId: string, environmentId: string, input: UpdateEnvironmentInput): Promise<Environment | null> { if (!(await this.ownerProject(ownerId, projectId))) return null; const ref = this.project(projectId).collection('environments').doc(environmentId); const result = await getFirestoreDb().runTransaction(async (transaction) => { const target = await transaction.get(ref); if (!target.exists) return false; if (input.isDefault === true) { const all = await transaction.get(ref.parent); all.docs.forEach((doc) => transaction.update(doc.ref, { isDefault: doc.id === environmentId, updatedAt: FieldValue.serverTimestamp() })); } transaction.set(ref, { ...input, updatedAt: FieldValue.serverTimestamp() }, { merge: true }); return true; }); if (!result) return null; const updated = await ref.get(); return mapEnvironment(environmentId, projectId, updated.data()!); }
  async delete(ownerId: string, projectId: string, environmentId: string): Promise<'deleted' | 'only-environment' | null> { if (!(await this.ownerProject(ownerId, projectId))) return null; const parent = this.project(projectId).collection('environments'); const ref = parent.doc(environmentId); const result = await getFirestoreDb().runTransaction(async (transaction) => { const all = await transaction.get(parent); const target = all.docs.find((doc) => doc.id === environmentId); if (!target) return null; if (all.size === 1) return 'only-environment' as const; transaction.delete(ref); if (target.data().isDefault) { const replacement = all.docs.find((doc) => doc.id !== environmentId)!; transaction.update(replacement.ref, { isDefault: true, updatedAt: FieldValue.serverTimestamp() }); } return 'deleted' as const; }); return result; }
}
