import { FieldValue, type Timestamp } from 'firebase-admin/firestore';
import { randomUUID } from 'node:crypto';
import type { CreateScanRequest, Project, Scan, ScanStatus } from '@visionqa/contracts';
import type { ScanRepository } from '../../contracts/index.js';
import { getFirestoreDb } from '../firebase-admin.js';

function iso(value: unknown): string | undefined { return value && typeof (value as Timestamp).toDate === 'function' ? (value as Timestamp).toDate().toISOString() : typeof value === 'string' ? value : undefined; }
function mapScan(id: string, data: Record<string, unknown>): Scan { return { id, projectId: String(data.projectId), environmentId: String(data.environmentId), createdBy: String(data.createdBy), type: data.type === 'full' ? 'full' : 'module', module: data.module as Scan['module'], checks: Array.isArray(data.checks) ? data.checks.map(String) : [], ...(Array.isArray(data.modules) ? { modules: data.modules as NonNullable<Scan['modules']> } : {}), requestedUrls: Array.isArray(data.requestedUrls) ? data.requestedUrls.map(String) : [], viewports: Array.isArray(data.viewports) ? data.viewports as Scan['viewports'] : [], browsers: Array.isArray(data.browsers) ? data.browsers as Scan['browsers'] : [], options: (data.options ?? {}) as Scan['options'], status: data.status as Scan['status'], progress: (data.progress ?? { completed: 0, total: 1, percent: 0 }) as Scan['progress'], createdAt: iso(data.createdAt) ?? new Date(0).toISOString(), updatedAt: iso(data.updatedAt) ?? new Date(0).toISOString(), ...(iso(data.startedAt) ? { startedAt: iso(data.startedAt) } : {}), ...(iso(data.completedAt) ? { completedAt: iso(data.completedAt) } : {}), ...(iso(data.cancelledAt) ? { cancelledAt: iso(data.cancelledAt) } : {}), ...(iso(data.cancellationRequestedAt) ? { cancellationRequestedAt: iso(data.cancellationRequestedAt) } : {}), ...(typeof data.failureCode === 'string' ? { failureCode: data.failureCode } : {}), ...(typeof data.failureMessage === 'string' ? { failureMessage: data.failureMessage } : {}) }; }

export class FirebaseScanRepository implements ScanRepository {
  private project(projectId: string) { return getFirestoreDb().collection('projects').doc(projectId); }
  private scans(projectId: string) { return this.project(projectId).collection('scans'); }
  private async owns(ownerId: string, projectId: string): Promise<boolean> { const snapshot = await this.project(projectId).get(); return snapshot.exists && snapshot.data()?.createdBy === ownerId; }
  async create(ownerId: string, project: Project, input: CreateScanRequest & { checks: string[]; requestedUrls: string[]; browsers: Scan['browsers']; viewports: Scan['viewports']; options: Scan['options'] }): Promise<Scan | null> { if (!(await this.owns(ownerId, project.id))) return null; const ref = this.scans(project.id).doc(randomUUID()); const now = FieldValue.serverTimestamp(); await ref.set({ id: ref.id, projectId: project.id, environmentId: input.environmentId, createdBy: ownerId, type: input.module === 'full-scan' ? 'full' : 'module', module: input.module, checks: input.checks, ...(input.modules ? { modules: input.modules } : {}), requestedUrls: input.requestedUrls, viewports: input.viewports, browsers: input.browsers, options: input.options, status: 'queued', progress: { completed: 0, total: 1, percent: 0 }, createdAt: now, updatedAt: now }); const created = await ref.get(); return mapScan(ref.id, created.data()!); }
  async findById(ownerId: string, projectId: string, scanId: string): Promise<Scan | null> { if (!(await this.owns(ownerId, projectId))) return null; const snapshot = await this.scans(projectId).doc(scanId).get(); return snapshot.exists ? mapScan(scanId, snapshot.data()!) : null; }
  async findByProject(ownerId: string, projectId: string): Promise<Scan[] | null> { if (!(await this.owns(ownerId, projectId))) return null; const snapshot = await this.scans(projectId).orderBy('createdAt', 'desc').get(); return snapshot.docs.map((doc) => mapScan(doc.id, doc.data())); }
  async updateStatus(ownerId: string, projectId: string, scanId: string, status: ScanStatus, fields: Partial<Pick<Scan, 'failureCode' | 'failureMessage' | 'progress'>> = {}): Promise<Scan | null> { if (!(await this.owns(ownerId, projectId))) return null; const ref = this.scans(projectId).doc(scanId); const current = await ref.get(); if (!current.exists) return null; await ref.set({ status, ...fields, ...(status === 'cancelled' ? { cancelledAt: FieldValue.serverTimestamp() } : {}), updatedAt: FieldValue.serverTimestamp() }, { merge: true }); const updated = await ref.get(); return mapScan(scanId, updated.data()!); }
  async markStarted(scanId: string): Promise<void> { const projects = await getFirestoreDb().collectionGroup('scans').where('id', '==', scanId).limit(1).get(); if (projects.empty) return; await projects.docs[0]!.ref.set({ status: 'running', startedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }, { merge: true }); }
  private async byId(scanId: string) { const snapshots = await getFirestoreDb().collectionGroup('scans').where('id', '==', scanId).limit(1).get(); return snapshots.empty ? null : snapshots.docs[0]!.ref; }
  async updateProgress(scanId: string, progress: Scan['progress']): Promise<void> { const ref = await this.byId(scanId); if (ref) await ref.set({ progress, updatedAt: FieldValue.serverTimestamp() }, { merge: true }); }
  async isCancellationRequested(scanId: string): Promise<boolean> { const ref = await this.byId(scanId); if (!ref) return true; const snapshot = await ref.get(); const data = snapshot.data() ?? {}; return data.status === 'cancelled' || Boolean(data.cancellationRequestedAt); }
  async complete(scanId: string, summary: Record<string, unknown>): Promise<void> { const ref = await this.byId(scanId); if (!ref || await this.isCancellationRequested(scanId)) return; await ref.set({ status: 'completed', summary, completedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }, { merge: true }); }
  async fail(scanId: string, failureCode: string, failureMessage: string): Promise<void> { const ref = await this.byId(scanId); if (!ref || await this.isCancellationRequested(scanId)) return; await ref.set({ status: 'failed', failureCode, failureMessage, updatedAt: FieldValue.serverTimestamp() }, { merge: true }); }
}
