import { FieldValue, type Timestamp } from 'firebase-admin/firestore';
import { createHash } from 'node:crypto';
import type { ResourceReference, ResourceStatus, ResourceType } from '@visionqa/contracts';
import type { ResourceRepository } from '../../contracts/storage.js';
import { getFirestoreDb } from '../firebase-admin.js';
const iso = (value: unknown): string | undefined => value && typeof (value as Timestamp).toDate === 'function' ? (value as Timestamp).toDate().toISOString() : typeof value === 'string' ? value : undefined;
const idFor = (resource: Pick<ResourceReference, 'scanId' | 'sourceUrl' | 'normalizedTargetUrl' | 'resourceType' | 'relationship'>) => createHash('sha256').update([resource.scanId, resource.sourceUrl, resource.normalizedTargetUrl, resource.resourceType, resource.relationship].join('|')).digest('hex').slice(0, 40);
function map(id: string, data: Record<string, unknown>): ResourceReference { return { id, scanId: String(data.scanId), projectId: String(data.projectId), ...(typeof data.sourcePageId === 'string' ? { sourcePageId: data.sourcePageId } : {}), sourceUrl: String(data.sourceUrl), targetUrl: String(data.targetUrl), normalizedTargetUrl: String(data.normalizedTargetUrl), resourceType: String(data.resourceType) as ResourceType, relationship: String(data.relationship), isInternal: Boolean(data.isInternal), discoveredAt: iso(data.discoveredAt) ?? new Date(0).toISOString(), ...(typeof data.status === 'string' ? { status: data.status as ResourceStatus } : {}), ...(typeof data.finalUrl === 'string' ? { finalUrl: data.finalUrl } : {}), ...(typeof data.statusCode === 'number' ? { statusCode: data.statusCode } : {}), redirectChain: Array.isArray(data.redirectChain) ? data.redirectChain.map(String) : [], ...(typeof data.durationMs === 'number' ? { durationMs: data.durationMs } : {}), ...(typeof data.errorCode === 'string' ? { errorCode: data.errorCode } : {}), ...(typeof data.errorMessage === 'string' ? { errorMessage: data.errorMessage } : {}), ...(typeof data.contentType === 'string' ? { contentType: data.contentType } : {}) }; }
export class FirebaseResourceRepository implements ResourceRepository {
  private collection(projectId: string, scanId: string) { return getFirestoreDb().collection('projects').doc(projectId).collection('scans').doc(scanId).collection('resources'); }
  async createMany(resources: Omit<ResourceReference, 'id' | 'discoveredAt'>[]): Promise<void> { for (let offset = 0; offset < resources.length; offset += 400) { const batch = getFirestoreDb().batch(); for (const resource of resources.slice(offset, offset + 400)) { const ref = this.collection(resource.projectId, resource.scanId).doc(idFor(resource)); batch.set(ref, { ...resource, id: ref.id, discoveredAt: FieldValue.serverTimestamp(), status: 'SKIPPED', redirectChain: resource.redirectChain ?? [] }, { merge: true }); } await batch.commit(); } }
  async findByScan(ownerId: string, projectId: string, scanId: string, options: { type?: ResourceType; status?: string; internal?: boolean; limit?: number; cursor?: string } = {}) { const project = await getFirestoreDb().collection('projects').doc(projectId).get(); if (!project.exists || project.data()?.createdBy !== ownerId) return { resources: [] }; let query = this.collection(projectId, scanId).orderBy('discoveredAt', 'desc').limit(Math.min(options.limit ?? 50, 100)) as FirebaseFirestore.Query; if (options.cursor) { const cursor = await this.collection(projectId, scanId).doc(options.cursor).get(); if (cursor.exists) query = query.startAfter(cursor); } const snapshot = await query.get(); const resources = snapshot.docs.map((doc) => map(doc.id, doc.data())).filter((item) => (!options.type || item.resourceType === options.type) && (!options.status || item.status === options.status) && (options.internal === undefined || item.isInternal === options.internal)); return { resources, ...(snapshot.size === Math.min(options.limit ?? 50, 100) && snapshot.docs.at(-1) ? { nextCursor: snapshot.docs.at(-1)!.id } : {}) }; }
  async findByTarget(scanId: string, normalizedTargetUrl: string) { const snapshot = await getFirestoreDb().collectionGroup('resources').where('scanId', '==', scanId).where('normalizedTargetUrl', '==', normalizedTargetUrl).get(); return snapshot.docs.map((doc) => map(doc.id, doc.data())); }
  async allByScan(projectId: string, scanId: string) { const snapshot = await this.collection(projectId, scanId).get(); return snapshot.docs.map((doc) => map(doc.id, doc.data())); }
  async updateResult(scanId: string, normalizedTargetUrl: string, result: Pick<ResourceReference, 'status' | 'finalUrl' | 'statusCode' | 'redirectChain' | 'durationMs' | 'errorCode' | 'errorMessage' | 'contentType'>): Promise<void> { const snapshot = await getFirestoreDb().collectionGroup('resources').where('scanId', '==', scanId).where('normalizedTargetUrl', '==', normalizedTargetUrl).get(); const batch = getFirestoreDb().batch(); snapshot.docs.forEach((doc) => batch.set(doc.ref, { ...result, updatedAt: FieldValue.serverTimestamp() }, { merge: true })); await batch.commit(); }
}
