import { FieldValue, type Timestamp } from 'firebase-admin/firestore';
import { createHash } from 'node:crypto';
import type { CustomCheckResult, CustomCheckSummary } from '@visionqa/contracts';
import type { CustomCheckResultRepository } from '../../contracts/index.js';
import { getFirestoreDb } from '../firebase-admin.js';

const iso = (value: unknown) => value && typeof (value as Timestamp).toDate === 'function' ? (value as Timestamp).toDate().toISOString() : typeof value === 'string' ? value : new Date(0).toISOString();
const map = (id: string, data: Record<string, unknown>): CustomCheckResult => ({ id, customCheckId: String(data.customCheckId), scanId: String(data.scanId), pageUrl: String(data.pageUrl), status: String(data.status) as CustomCheckResult['status'], actual: (data.actual === null || typeof data.actual === 'string' || typeof data.actual === 'number' || typeof data.actual === 'boolean' ? data.actual : null) as NonNullable<CustomCheckResult['actual']> | null, expected: (data.expected === null || typeof data.expected === 'string' || typeof data.expected === 'number' || typeof data.expected === 'boolean' ? data.expected : null) as NonNullable<CustomCheckResult['expected']> | null, message: String(data.message ?? ''), ...(typeof data.browser === 'string' ? { browser: data.browser as CustomCheckResult['browser'] } : {}), ...(data.viewport && typeof data.viewport === 'object' ? { viewport: data.viewport as CustomCheckResult['viewport'] } : {}), ...(typeof data.elementRef === 'string' ? { elementRef: data.elementRef } : {}), ...(typeof data.evidenceId === 'string' ? { evidenceId: data.evidenceId } : {}), evaluatedAt: iso(data.evaluatedAt) });

export class FirebaseCustomCheckResultRepository implements CustomCheckResultRepository {
  private project(projectId: string) { return getFirestoreDb().collection('projects').doc(projectId); }
  private results(projectId: string, scanId: string) { return this.project(projectId).collection('scans').doc(scanId).collection('customResults'); }
  private async owns(ownerId: string, projectId: string, scanId: string) { const [project, scan] = await Promise.all([this.project(projectId).get(), this.project(projectId).collection('scans').doc(scanId).get()]); return project.exists && project.data()?.createdBy === ownerId && scan.exists; }
  async create(input: Omit<CustomCheckResult, 'id'> & { projectId: string }) { const ref = this.results(input.projectId, input.scanId).doc(createHash('sha256').update(`${input.scanId}|${input.customCheckId}|${input.pageUrl}|${input.browser ?? ''}|${input.viewport?.width ?? ''}x${input.viewport?.height ?? ''}`).digest('hex').slice(0, 40)); const { projectId: _projectId, ...data } = input; void _projectId; await ref.set({ ...data, evaluatedAt: FieldValue.serverTimestamp() }, { merge: true }); return map(ref.id, (await ref.get()).data()!); }
  async findByScan(ownerId: string, projectId: string, scanId: string, options: { customCheckId?: string; status?: CustomCheckResult['status']; limit?: number; cursor?: string } = {}) { if (!(await this.owns(ownerId, projectId, scanId))) return { results: [] }; const limit = Math.min(options.limit ?? 100, 100); let query = this.results(projectId, scanId).orderBy('evaluatedAt', 'desc').limit(limit) as FirebaseFirestore.Query; if (options.cursor) { const cursor = await this.results(projectId, scanId).doc(options.cursor).get(); if (cursor.exists) query = query.startAfter(cursor); } const snapshot = await query.get(); const results = snapshot.docs.map((doc) => map(doc.id, doc.data())).filter((result) => (!options.customCheckId || result.customCheckId === options.customCheckId) && (!options.status || result.status === options.status)); return { results, ...(snapshot.size === limit && snapshot.docs.at(-1) ? { nextCursor: snapshot.docs.at(-1)!.id } : {}) }; }
  async summary(ownerId: string, projectId: string, scanId: string): Promise<CustomCheckSummary> { const { results } = await this.findByScan(ownerId, projectId, scanId, { limit: 100 }); const byCheck: CustomCheckSummary['byCheck'] = {}; for (const result of results) { const item = byCheck[result.customCheckId] ?? { passed: 0, failed: 0, skipped: 0, errors: 0 }; if (result.status === 'PASS') item.passed++; if (result.status === 'FAIL') item.failed++; if (result.status === 'SKIPPED') item.skipped++; if (result.status === 'ERROR') item.errors++; byCheck[result.customCheckId] = item; } return { checksExecuted: results.length, passed: results.filter((result) => result.status === 'PASS').length, failed: results.filter((result) => result.status === 'FAIL').length, skipped: results.filter((result) => result.status === 'SKIPPED').length, errors: results.filter((result) => result.status === 'ERROR').length, pagesChecked: new Set(results.map((result) => result.pageUrl)).size, findings: results.filter((result) => result.status === 'FAIL').length, byCheck }; }
}
