import { FieldValue, type Timestamp } from 'firebase-admin/firestore';
import { createHash } from 'node:crypto';
import type { Issue, IssueStatus, QaModule, Severity } from '@visionqa/contracts';
import type { IssueRepository } from '../../contracts/storage.js';
import { getFirestoreDb } from '../firebase-admin.js';
const iso = (value: unknown): string | undefined => value && typeof (value as Timestamp).toDate === 'function' ? (value as Timestamp).toDate().toISOString() : typeof value === 'string' ? value : undefined;
function map(id: string, data: Record<string, unknown>): Issue { const firstSeenAt = iso(data.firstSeenAt) ?? new Date(0).toISOString(); const lastSeenAt = iso(data.lastSeenAt) ?? firstSeenAt; const createdAt = iso(data.createdAt) ?? firstSeenAt; return { id, projectId: String(data.projectId), detectorId: String(data.detectorId), module: String(data.module) as QaModule, severity: String(data.severity) as Severity, status: String(data.status ?? 'OPEN') as IssueStatus, title: String(data.title), message: String(data.message), fingerprint: String(data.fingerprint), primaryUrl: String(data.primaryUrl), firstSeenAt, lastSeenAt, occurrenceCount: Number(data.occurrenceCount ?? 0), createdAt, updatedAt: iso(data.updatedAt) ?? lastSeenAt }; }
export class FirebaseIssueRepository implements IssueRepository {
  private collection(projectId: string) { return getFirestoreDb().collection('projects').doc(projectId).collection('issues'); }
  async upsertFinding(input: Omit<Issue, 'id' | 'firstSeenAt' | 'lastSeenAt' | 'occurrenceCount' | 'createdAt' | 'updatedAt' | 'status'> & { scanId: string; evidence: Record<string, unknown>; pageId?: string }): Promise<Issue> { const id = createHash('sha256').update(`${input.projectId}|${input.fingerprint}`).digest('hex').slice(0, 40); const ref = this.collection(input.projectId).doc(id); const existing = await ref.get(); const now = FieldValue.serverTimestamp(); const status = existing.exists && existing.data()?.status === 'FIXED' ? 'REOPENED' : existing.exists ? existing.data()?.status ?? 'OPEN' : 'OPEN'; await ref.set({ projectId: input.projectId, detectorId: input.detectorId, module: input.module, severity: input.severity, title: input.title, message: input.message, fingerprint: input.fingerprint, primaryUrl: input.primaryUrl, status, ...(existing.exists ? {} : { firstSeenAt: now, createdAt: now, occurrenceCount: 0 }), lastSeenAt: now, updatedAt: now }, { merge: true }); await this.addOccurrence({ issueId: ref.id, projectId: input.projectId, scanId: input.scanId, ...(input.pageId ? { pageId: input.pageId } : {}), sourceUrl: input.primaryUrl, targetUrl: input.primaryUrl, evidence: input.evidence }); await ref.update({ occurrenceCount: FieldValue.increment(1), updatedAt: now }); const saved = await ref.get(); return map(ref.id, saved.data()!); }
  async findByProject(ownerId: string, projectId: string, options: { severity?: string; status?: IssueStatus; module?: string; detectorId?: string; scanId?: string; pageUrl?: string; limit?: number; cursor?: string } = {}) { const project = await getFirestoreDb().collection('projects').doc(projectId).get(); if (!project.exists || project.data()?.createdBy !== ownerId) return { issues: [] }; let query = this.collection(projectId).orderBy('updatedAt', 'desc').limit(Math.min(options.limit ?? 50, 100)) as FirebaseFirestore.Query; if (options.cursor) { const cursor = await this.collection(projectId).doc(options.cursor).get(); if (cursor.exists) query = query.startAfter(cursor); } const snapshot = await query.get(); const issues = snapshot.docs.map((doc) => map(doc.id, doc.data())).filter((item) => (!options.severity || item.severity === options.severity) && (!options.status || item.status === options.status) && (!options.module || item.module === options.module) && (!options.detectorId || item.detectorId === options.detectorId) && (!options.pageUrl || item.primaryUrl.includes(options.pageUrl))); return { issues, ...(snapshot.size === Math.min(options.limit ?? 50, 100) && snapshot.docs.at(-1) ? { nextCursor: snapshot.docs.at(-1)!.id } : {}) }; }
  async findById(ownerId: string, projectId: string, issueId: string) { const project = await getFirestoreDb().collection('projects').doc(projectId).get(); if (!project.exists || project.data()?.createdBy !== ownerId) return null; const doc = await this.collection(projectId).doc(issueId).get(); return doc.exists ? map(doc.id, doc.data()!) : null; }
  async addOccurrence(input: Omit<import('@visionqa/contracts').IssueOccurrence, 'id' | 'detectedAt'>): Promise<void> { await this.collection(input.projectId).doc(input.issueId).collection('occurrences').add({ ...input, detectedAt: FieldValue.serverTimestamp() }); }
  async updateStatus(ownerId: string, projectId: string, issueId: string, status: IssueStatus) { const project = await getFirestoreDb().collection('projects').doc(projectId).get(); if (!project.exists || project.data()?.createdBy !== ownerId) return null; const ref = this.collection(projectId).doc(issueId); if (!(await ref.get()).exists) return null; await ref.set({ status, updatedAt: FieldValue.serverTimestamp() }, { merge: true }); const doc = await ref.get(); return map(doc.id, doc.data()!); }
}
