import { request as httpRequest } from 'node:http';
import { request as httpsRequest } from 'node:https';
import type { IncomingMessage } from 'node:http';
import { NetworkPolicyError, OutboundNetworkPolicy } from './index.js';

export type SecureHttpResponse = { url: string; statusCode: number; contentType: string; body: string; redirectChain: string[] };
export class SecureHttpError extends Error { constructor(public readonly code: string, message: string) { super(message); this.name = 'SecureHttpError'; } }
export type SecureHttpOptions = { policy?: OutboundNetworkPolicy; timeoutMs?: number; maxBytes?: number; maxRedirects?: number; userAgent?: string; acceptedContentTypes?: string[] };
export class SecureHttpClient {
  private readonly policy: OutboundNetworkPolicy;
  private readonly options: Required<Omit<SecureHttpOptions, 'policy'>>;
  constructor(options: SecureHttpOptions = {}) { this.policy = options.policy ?? new OutboundNetworkPolicy(); this.options = { timeoutMs: options.timeoutMs ?? 15000, maxBytes: options.maxBytes ?? 5 * 1024 * 1024, maxRedirects: options.maxRedirects ?? 5, userAgent: options.userAgent ?? 'VisionQA-HTTP/0.1', acceptedContentTypes: options.acceptedContentTypes ?? ['text/html', 'application/xhtml+xml', 'application/xml', 'text/xml', 'text/plain', 'image/', 'font/', 'audio/', 'video/', 'application/javascript', 'text/javascript', 'text/css'] }; }
  async get(rawUrl: string, signal?: AbortSignal): Promise<SecureHttpResponse> { let current = rawUrl; const chain: string[] = []; for (let count = 0; count <= this.options.maxRedirects; count++) { const resolved = await this.policy.validateAndResolve(current); const response = await this.request(resolved.url, resolved.addresses[0]!, signal); const location = response.headers.location; if (location && [301, 302, 303, 307, 308].includes(response.statusCode)) { if (count === this.options.maxRedirects) throw new SecureHttpError('TOO_MANY_REDIRECTS', 'Too many redirects.'); const next = new URL(location, resolved.url).toString(); if (chain.includes(next) || next === current) throw new SecureHttpError('REDIRECT_LOOP', 'Redirect loop detected.'); chain.push(current); current = next; continue; } const contentType = String(response.headers['content-type'] ?? '').split(';', 1)[0]!.trim().toLowerCase(); const accepted = this.options.acceptedContentTypes.some((type) => type.endsWith('/') ? contentType.startsWith(type) : contentType === type); return { url: current, statusCode: response.statusCode, contentType, body: accepted ? response.body : '', redirectChain: chain }; } throw new SecureHttpError('TOO_MANY_REDIRECTS', 'Too many redirects.'); }
  private request(url: URL, address: string, signal?: AbortSignal): Promise<{ statusCode: number; headers: IncomingMessage['headers']; body: string }> { return new Promise((resolve, reject) => { if (signal?.aborted) return reject(new SecureHttpError('CANCELLED', 'Request cancelled.')); const requester = url.protocol === 'https:' ? httpsRequest : httpRequest; const req = requester({ protocol: url.protocol, hostname: address, port: url.port || undefined, path: `${url.pathname}${url.search}`, headers: { host: url.host, accept: '*/*', 'user-agent': this.options.userAgent }, servername: url.hostname, lookup: (_hostname, _options, callback) => callback(null, address, address.includes(':') ? 6 : 4), timeout: this.options.timeoutMs }, (response) => { const chunks: Buffer[] = []; let size = 0; response.on('data', (chunk: Buffer) => { size += chunk.length; if (size > this.options.maxBytes) { response.destroy(); reject(new SecureHttpError('RESPONSE_TOO_LARGE', 'Response exceeds the configured limit.')); } else chunks.push(chunk); }); response.on('end', () => resolve({ statusCode: response.statusCode ?? 0, headers: response.headers, body: Buffer.concat(chunks).toString('utf8') })); response.on('error', (error) => reject(new SecureHttpError('CONNECTION_FAILED', error.message))); }); const abort = () => { req.destroy(); reject(new SecureHttpError('CANCELLED', 'Request cancelled.')); }; signal?.addEventListener('abort', abort, { once: true }); req.on('timeout', () => { req.destroy(); reject(new SecureHttpError('TIMEOUT', 'Request timed out.')); }); req.on('error', (error) => reject(signal?.aborted ? new SecureHttpError('CANCELLED', 'Request cancelled.') : new SecureHttpError('CONNECTION_FAILED', error.message))); req.end(); }); }
}
export function secureHttpFailure(error: unknown): { code: string; message: string } { if (error instanceof NetworkPolicyError) return { code: 'NETWORK_POLICY_BLOCKED', message: error.message }; if (error instanceof SecureHttpError) return { code: error.code, message: error.message }; return { code: 'CONNECTION_FAILED', message: 'The resource could not be fetched.' }; }
