import type { BrowserFact, BrowserPageExecution, CreateScanRequest, CrawlPage, CrawlSummary, Evidence, Scan, ScanProgressResponse } from '@visionqa/contracts';
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000';
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${apiUrl}${path}`, { ...init, credentials: 'include', headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) } }); if (!response.ok) { const body = await response.json().catch(() => null) as { message?: string } | null; throw new Error(body?.message ?? 'Unable to complete scan request.'); } return response.json() as Promise<T>; }
export async function createScan(projectId: string, input: CreateScanRequest): Promise<Scan> { return (await request<{ scan: Scan }>(`/api/v1/projects/${projectId}/scans`, { method: 'POST', body: JSON.stringify(input) })).scan; }
export async function createFullScan(projectId: string, input: Omit<CreateScanRequest, 'module'> & { modules: NonNullable<CreateScanRequest['modules']> }): Promise<Scan> { return (await request<{ scan: Scan }>(`/api/v1/projects/${projectId}/scans/full`, { method: 'POST', body: JSON.stringify({ ...input, module: 'full-scan' }) })).scan; }
export async function getScans(projectId: string): Promise<Scan[]> { return (await request<{ scans: Scan[] }>(`/api/v1/projects/${projectId}/scans`)).scans; }
export async function getScan(projectId: string, scanId: string): Promise<Scan> { return (await request<{ scan: Scan }>(`/api/v1/projects/${projectId}/scans/${scanId}`)).scan; }
export async function getScanProgress(projectId: string, scanId: string): Promise<ScanProgressResponse> { return request<ScanProgressResponse>(`/api/v1/projects/${projectId}/scans/${scanId}/progress`); }
export async function cancelScan(projectId: string, scanId: string): Promise<Scan> { return (await request<{ scan: Scan }>(`/api/v1/projects/${projectId}/scans/${scanId}/cancel`, { method: 'POST' })).scan; }
export async function getFullScanSummary(projectId: string, scanId: string) { return request<import('@visionqa/contracts').FullScanSummary>(`/api/v1/projects/${projectId}/scans/${scanId}/full/summary`); }
export async function getFullScanModules(projectId: string, scanId: string) { return request<{ modules: import('@visionqa/contracts').FullScanModuleState[] }>(`/api/v1/projects/${projectId}/scans/${scanId}/full/modules`); }
export async function getFullScanProgress(projectId: string, scanId: string) { return request<{ scanId: string; status: import('@visionqa/contracts').ScanStatus; progress: import('@visionqa/contracts').FullScanProgress }>(`/api/v1/projects/${projectId}/scans/${scanId}/full/progress`); }
export async function getScanIssues(projectId: string, scanId: string) { return request<{ issues: import('@visionqa/contracts').Issue[] }>(`/api/v1/projects/${projectId}/issues?scanId=${encodeURIComponent(scanId)}&limit=100`); }
export async function getCrawlPages(projectId: string, scanId: string, query = ''): Promise<{ pages: CrawlPage[]; nextCursor?: string }> { return request<{ pages: CrawlPage[]; nextCursor?: string }>(`/api/v1/projects/${projectId}/scans/${scanId}/crawl/pages${query ? `?${query}` : ''}`); }
export async function getCrawlSummary(projectId: string, scanId: string): Promise<CrawlSummary> { return request<CrawlSummary>(`/api/v1/projects/${projectId}/scans/${scanId}/crawl/summary`); }
export async function getCrawlQuality(projectId: string, scanId: string, type: 'robots' | 'sitemap'): Promise<Record<string, unknown>> { return request<Record<string, unknown>>(`/api/v1/projects/${projectId}/scans/${scanId}/crawl/${type}`); }
export async function getCrawlComparison(projectId: string, scanId: string): Promise<{ matched: string[]; crawlOnly: string[]; sitemapOnly: string[] }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/crawl/comparison`); }
export async function getBrowserPages(projectId: string, scanId: string): Promise<{ executions: BrowserPageExecution[]; nextCursor?: string }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/browser/pages`); }
export async function getBrowserFacts(projectId: string, scanId: string, kind: 'console' | 'network'): Promise<{ facts: BrowserFact[]; nextCursor?: string }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/browser/${kind}`); }
export async function getBrowserSummary(projectId: string, scanId: string): Promise<{ pagesExecuted: number; uniquePages: number; consoleErrors: number; javascriptErrors: number; failedRequests: number; httpErrors: number; networkPolicyBlocked: number; screenshots: number }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/browser/summary`); }
export async function getScanEvidence(projectId: string, scanId: string): Promise<{ evidence: Evidence[]; nextCursor?: string }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/evidence`); }
export async function getCustomCheckSummary(projectId: string, scanId: string) { return request<import('@visionqa/contracts').CustomCheckSummary>(`/api/v1/projects/${projectId}/scans/${scanId}/custom/summary`); }
export async function getCustomCheckResults(projectId: string, scanId: string, query = '') { return request<{ results: import('@visionqa/contracts').CustomCheckResult[]; nextCursor?: string }>(`/api/v1/projects/${projectId}/scans/${scanId}/custom/results${query ? `?${query}` : ''}`); }
export async function getCustomCheckFindings(projectId: string, scanId: string, query = '') { return request<{ findings: import('@visionqa/contracts').Issue[]; nextCursor?: string }>(`/api/v1/projects/${projectId}/scans/${scanId}/custom/findings${query ? `?${query}` : ''}`); }
export async function getEvidence(projectId: string, evidenceId: string): Promise<Evidence & { url: string }> { return request(`/api/v1/projects/${projectId}/evidence/${evidenceId}`); }
export async function getVisualSummary(projectId: string, scanId: string): Promise<{ pagesChecked: number; viewportsExecuted: number; findings: number; issues: number; overflowPages: number; obstructions: number; detectors: Record<string, { executed: boolean; findings?: number }>; byDetector: Record<string, number>; bySeverity: Record<string, number> }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/visual/summary`); }
export async function getVisualFindings(projectId: string, scanId: string, query = ''): Promise<{ findings: import('@visionqa/contracts').Issue[]; nextCursor?: string }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/visual/findings${query ? `?${query}` : ''}`); }
export async function getVisualPages(projectId: string, scanId: string): Promise<{ executions: Array<{ executionId: string; pageUrl: string; browser: string; viewport: { width: number; height: number }; status: string; durationMs?: number; findingsCount: number; originalScreenshotEvidenceId?: string }>; nextCursor?: string }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/visual/pages`); }
export async function getVisualEvidence(projectId: string, scanId: string, query = ''): Promise<{ evidence: Evidence[]; nextCursor?: string }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/visual/evidence${query ? `?${query}` : ''}`); }
export async function getAccessibilitySummary(projectId: string, scanId: string) { return request<{ pagesChecked: number; findings: number; high: number; medium: number; low: number; info: number; byDetector: Record<string, number>; detectors: Record<string, { executed: boolean; findings: number }> }>(`/api/v1/projects/${projectId}/scans/${scanId}/accessibility/summary`); }
export async function getAccessibilityFindings(projectId: string, scanId: string, query = '') { return request<{ findings: import('@visionqa/contracts').Issue[]; nextCursor?: string }>(`/api/v1/projects/${projectId}/scans/${scanId}/accessibility/findings${query ? `?${query}` : ''}`); }
export async function getSeoSummary(projectId: string, scanId: string) { return request<{ pagesChecked: number; indexable: number; nonIndexable: number; missingTitles: number; missingDescriptions: number; canonicalIssues: number; metadataFindings: number; byDetector: Record<string, number>; detectors: Record<string, { executed: boolean; findings: number }> }>(`/api/v1/projects/${projectId}/scans/${scanId}/seo/summary`); }
export async function getSeoFindings(projectId: string, scanId: string, query = '') { return request<{ findings: import('@visionqa/contracts').Issue[]; nextCursor?: string }>(`/api/v1/projects/${projectId}/scans/${scanId}/seo/findings${query ? `?${query}` : ''}`); }
export async function getPerformanceSummary(projectId: string, scanId: string) { return request<{ pagesChecked: number; averageLoadMs: number | null; averageLcpMs: number | null; worstLcpMs: number | null; averageCls: number | null; totalRequests: number; totalTransferBytes: number }>(`/api/v1/projects/${projectId}/scans/${scanId}/performance/summary`); }
export async function getPerformancePages(projectId: string, scanId: string) { return request<{ executions: Array<{ pageUrl: string; browser: string; viewport: { width: number; height: number }; status: string; performance?: import('@visionqa/contracts').PerformanceSnapshot }> }>(`/api/v1/projects/${projectId}/scans/${scanId}/performance/pages`); }
export async function getPerformanceResources(projectId: string, scanId: string, query = '') { return request<{ resources: Array<{ displayUrl: string; url: string; type: string; durationMs: number | null; transferSize: number | null; status: number | null; pageUrl: string; browser: string }>; nextCursor?: string }>(`/api/v1/projects/${projectId}/scans/${scanId}/performance/resources${query ? `?${query}` : ''}`); }
export async function getPerformanceFindings(projectId: string, scanId: string, query = '') { return request<{ findings: import('@visionqa/contracts').Issue[]; nextCursor?: string }>(`/api/v1/projects/${projectId}/scans/${scanId}/performance/findings${query ? `?${query}` : ''}`); }
export async function getCompatibilitySummary(projectId: string, scanId: string) { return request<import('@visionqa/contracts').CompatibilitySummary>(`/api/v1/projects/${projectId}/scans/${scanId}/compatibility/summary`); }
export async function getCompatibilityBrowsers(projectId: string, scanId: string) { return request<{ browsers: Array<{ browser: string; version?: string; availability: string; pagesExecuted: number; consoleErrors: number; failedRequests: number; status: string }> }>(`/api/v1/projects/${projectId}/scans/${scanId}/compatibility/browsers`); }
export async function getCompatibilityFindings(projectId: string, scanId: string, query = '') { return request<{ findings: Array<import('@visionqa/contracts').Issue | import('@visionqa/contracts').CompatibilityFinding>; nextCursor?: string }>(`/api/v1/projects/${projectId}/scans/${scanId}/compatibility/findings${query ? `?${query}` : ''}`); }
