import type { BrowserFact, BrowserPageExecution, CreateScanRequest, CrawlPage, CrawlSummary, Evidence, Scan, ScanProgressResponse } from '@visionqa/contracts';
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000';
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${apiUrl}${path}`, { ...init, credentials: 'include', headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) } }); if (!response.ok) { const body = await response.json().catch(() => null) as { message?: string } | null; throw new Error(body?.message ?? 'Unable to complete scan request.'); } return response.json() as Promise<T>; }
export async function createScan(projectId: string, input: CreateScanRequest): Promise<Scan> { return (await request<{ scan: Scan }>(`/api/v1/projects/${projectId}/scans`, { method: 'POST', body: JSON.stringify(input) })).scan; }
export async function getScans(projectId: string): Promise<Scan[]> { return (await request<{ scans: Scan[] }>(`/api/v1/projects/${projectId}/scans`)).scans; }
export async function getScan(projectId: string, scanId: string): Promise<Scan> { return (await request<{ scan: Scan }>(`/api/v1/projects/${projectId}/scans/${scanId}`)).scan; }
export async function getScanProgress(projectId: string, scanId: string): Promise<ScanProgressResponse> { return request<ScanProgressResponse>(`/api/v1/projects/${projectId}/scans/${scanId}/progress`); }
export async function cancelScan(projectId: string, scanId: string): Promise<Scan> { return (await request<{ scan: Scan }>(`/api/v1/projects/${projectId}/scans/${scanId}/cancel`, { method: 'POST' })).scan; }
export async function getCrawlPages(projectId: string, scanId: string, query = ''): Promise<{ pages: CrawlPage[]; nextCursor?: string }> { return request<{ pages: CrawlPage[]; nextCursor?: string }>(`/api/v1/projects/${projectId}/scans/${scanId}/crawl/pages${query ? `?${query}` : ''}`); }
export async function getCrawlSummary(projectId: string, scanId: string): Promise<CrawlSummary> { return request<CrawlSummary>(`/api/v1/projects/${projectId}/scans/${scanId}/crawl/summary`); }
export async function getCrawlQuality(projectId: string, scanId: string, type: 'robots' | 'sitemap'): Promise<Record<string, unknown>> { return request<Record<string, unknown>>(`/api/v1/projects/${projectId}/scans/${scanId}/crawl/${type}`); }
export async function getCrawlComparison(projectId: string, scanId: string): Promise<{ matched: string[]; crawlOnly: string[]; sitemapOnly: string[] }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/crawl/comparison`); }
export async function getBrowserPages(projectId: string, scanId: string): Promise<{ executions: BrowserPageExecution[]; nextCursor?: string }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/browser/pages`); }
export async function getBrowserFacts(projectId: string, scanId: string, kind: 'console' | 'network'): Promise<{ facts: BrowserFact[]; nextCursor?: string }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/browser/${kind}`); }
export async function getBrowserSummary(projectId: string, scanId: string): Promise<{ pagesExecuted: number; uniquePages: number; consoleErrors: number; javascriptErrors: number; failedRequests: number; httpErrors: number; networkPolicyBlocked: number; screenshots: number }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/browser/summary`); }
export async function getScanEvidence(projectId: string, scanId: string): Promise<{ evidence: Evidence[]; nextCursor?: string }> { return request(`/api/v1/projects/${projectId}/scans/${scanId}/evidence`); }
export async function getEvidence(projectId: string, evidenceId: string): Promise<Evidence & { url: string }> { return request(`/api/v1/projects/${projectId}/evidence/${evidenceId}`); }
