'use client';
import Link from 'next/link';
import { useState } from 'react';
import type { Scan } from '@visionqa/contracts';
import { useProjects } from '@/features/projects/project-context';
import { createScan } from '@/features/scans/scan.service';
import { ScanStatusBadge } from '@/features/scans/components/ScanStatusBadge';
import { ScanTargetInput } from '@/features/scans/components/ScanTargetInput';
export default function CrawlPage() { const { selectedProject } = useProjects(); const [url, setUrl] = useState(''); const [scope, setScope] = useState<Scan['scope']>('site'); const [maxPages, setMaxPages] = useState('100'); const [maxDepth, setMaxDepth] = useState('3'); const [scan, setScan] = useState<Scan | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const start = async () => { if (!selectedProject) return; setBusy(true); setError(null); try { setScan(await createScan(selectedProject.id, { url, scope, module: 'crawl-site-structure', checks: ['crawl'], options: { maxPages: Number(maxPages), maxDepth: Number(maxDepth), sameOriginOnly: true } })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create crawl.'); } finally { setBusy(false); } }; return <section className="scan-page"><p className="dashboard-eyebrow">QA CHECK · CRAWL</p><h1 className="dashboard-page-title">Crawl &amp; Site Structure</h1><p className="dashboard-lead">Discover pages from any HTTP or HTTPS starting URL.</p><div className="scan-config-card"><ScanTargetInput value={url} onChange={setUrl} error={error} /><label className="block text-sm font-semibold text-[#542064]">Scope<select className="liquid-control mt-2 block w-full rounded-xl px-4 py-3" value={scope} onChange={(event) => setScope(event.target.value as Scan['scope'])}><option value="site">Site</option><option value="start-url">Start URL</option><option value="path">Path</option></select></label><div className="scan-settings-grid"><label>Max pages<input type="number" min="1" max="1000" value={maxPages} onChange={(event) => setMaxPages(event.target.value)} /></label><label>Max depth<input type="number" min="0" max="20" value={maxDepth} onChange={(event) => setMaxDepth(event.target.value)} /></label></div><button className="dashboard-primary-button" type="button" disabled={busy || !selectedProject || !url.trim()} onClick={() => void start()}>{busy ? 'Starting…' : 'Start Crawl'}</button></div>{scan && <div className="scan-confirmation" role="status"><div><h2>Scan queued</h2><p>{scan.target?.requestedUrl}</p></div><ScanStatusBadge status={scan.status} /><Link className="dashboard-card-action" href={`/scans/${scan.id}`}>View scan →</Link></div>}</section>; }
