'use client';
import { useState } from 'react';
import Link from 'next/link';
import type { Scan } from '@visionqa/contracts';
import { ActiveQaTarget } from '@/features/projects/components/ActiveQaTarget';
import { useProjects } from '@/features/projects/project-context';
import { createScan } from '@/features/scans/scan.service';
import { ScanStatusBadge } from '@/features/scans/components/ScanStatusBadge';

export default function CrawlPage() { const { selectedProject, selectedEnvironment } = useProjects(); const [maxPages, setMaxPages] = useState('100'); const [maxDepth, setMaxDepth] = useState('3'); const [sameOriginOnly, setSameOriginOnly] = useState(true); const [scan, setScan] = useState<Scan | null>(null); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false); const start = async () => { if (!selectedProject || !selectedEnvironment) return; setSubmitting(true); setError(null); try { setScan(await createScan(selectedProject.id, { environmentId: selectedEnvironment.id, module: 'crawl-site-structure', checks: ['crawl'], options: { maxPages: Number(maxPages), maxDepth: Number(maxDepth), sameOriginOnly } })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create crawl.'); } finally { setSubmitting(false); } }; return <section className="scan-page"><p className="dashboard-eyebrow">QA CHECK · CRAWL</p><h1 className="dashboard-page-title">Crawl &amp; Site Structure</h1><p className="dashboard-lead">Discover pages for the active environment with bounded, secure HTTP crawling.</p><ActiveQaTarget /><div className="scan-config-card"><h2>Crawl settings</h2><div className="scan-settings-grid"><label>Max pages<input type="number" min="1" max="1000" value={maxPages} onChange={(event) => setMaxPages(event.target.value)} /></label><label>Max depth<input type="number" min="0" max="20" value={maxDepth} onChange={(event) => setMaxDepth(event.target.value)} /></label></div><label className="scan-check"><input type="checkbox" checked={sameOriginOnly} onChange={(event) => setSameOriginOnly(event.target.checked)} /> <span>Same origin only</span></label><div className="scan-check scan-check-disabled"><input type="checkbox" disabled /> <span>Robots.txt</span><small>Coming soon</small></div><div className="scan-check scan-check-disabled"><input type="checkbox" disabled /> <span>Sitemap</span><small>Coming soon</small></div><button className="dashboard-primary-button" type="button" disabled={submitting || !selectedProject || !selectedEnvironment} onClick={() => void start()}>{submitting ? 'Starting…' : 'Start Crawl'}</button>{error && <p className="scan-error" role="alert">{error}</p>}</div>{scan && <div className="scan-confirmation" role="status"><div><h2>Scan queued</h2><p>{selectedEnvironment?.name} · {scan.checks.join(', ')}</p></div><ScanStatusBadge status={scan.status} /><Link className="dashboard-card-action" href={`/scans/${scan.id}`}>View scan <b>→</b></Link></div>}</section>; }
