'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useProjects } from '@/features/projects/project-context';
import { createScan } from '@/features/scans/scan.service';
import { ActiveQaTarget } from '@/features/projects/components/ActiveQaTarget';
import type { Scan } from '@visionqa/contracts';
const checks = [['text-overlap', 'Text overlap'], ['element-overlap', 'Element overlap'], ['horizontal-overflow', 'Horizontal overflow'], ['viewport-overflow', 'Viewport overflow']] as const;
const viewports = { mobile: { width: 390, height: 844 }, tablet: { width: 768, height: 1024 }, desktop: { width: 1366, height: 768 }, wide: { width: 1920, height: 1080 } };
export default function VisualResponsivePage() { const { selectedProject, selectedEnvironment } = useProjects(); const [selected, setSelected] = useState<string[]>(checks.map(([id]) => id)); const [sizes, setSizes] = useState<string[]>(['mobile', 'desktop']); const [scan, setScan] = useState<Scan | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const run = async () => { if (!selectedProject || !selectedEnvironment || !selected.length || !sizes.length) return; setBusy(true); setError(null); try { setScan(await createScan(selectedProject.id, { environmentId: selectedEnvironment.id, module: 'visual-responsive', checks: selected, browsers: ['chromium'], viewports: sizes.map((size) => viewports[size as keyof typeof viewports]) })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to start visual validation.'); } finally { setBusy(false); } }; return <section className="scan-page"><p className="dashboard-eyebrow">QA CHECK · VISUAL</p><h1 className="dashboard-page-title">Visual &amp; Responsive</h1><p className="dashboard-lead">Find deterministic layout problems across the selected Chromium viewports.</p><ActiveQaTarget /><div className="scan-config-card"><h2>Checks to run</h2>{checks.map(([id, label]) => <label className="scan-check" key={id}><input type="checkbox" checked={selected.includes(id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, id] : current.filter((item) => item !== id))} /> <span>{label}</span></label>)}<h2>Viewports</h2>{Object.entries(viewports).map(([id, viewport]) => <label className="scan-check" key={id}><input type="checkbox" checked={sizes.includes(id)} onChange={(event) => setSizes((current) => event.target.checked ? [...current, id] : current.filter((item) => item !== id))} /> <span>{id[0]!.toUpperCase() + id.slice(1)} · {viewport.width} × {viewport.height}</span></label>)}<button className="dashboard-primary-button" type="button" disabled={busy || !selected.length || !sizes.length || !selectedProject || !selectedEnvironment} onClick={() => void run()}>{busy ? 'Starting…' : 'Run Visual Check'}</button>{error && <p className="scan-error" role="alert">{error}</p>}</div>{scan && <div className="scan-confirmation" role="status"><div><h2>Visual scan queued</h2><p>{selectedEnvironment?.name} · {scan.checks.join(', ')}</p></div><Link className="dashboard-card-action" href={`/scans/${scan.id}`}>View scan →</Link></div>}</section>; }
