'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useProjects } from '@/features/projects/project-context';
import { createScan } from '@/features/scans/scan.service';
import type { Scan } from '@visionqa/contracts';
import { ScanTargetInput } from '@/features/scans/components/ScanTargetInput';

const viewports = { mobile: { width: 390, height: 844 }, tablet: { width: 768, height: 1024 }, desktop: { width: 1366, height: 768 }, wide: { width: 1920, height: 1080 } };
const checks = [['text-overlap', 'Text overlap'], ['element-overlap', 'Element overlap'], ['clipped-content', 'Clipped content'], ['horizontal-overflow', 'Horizontal overflow'], ['viewport-overflow', 'Viewport overflow'], ['fixed-element-obstruction', 'Fixed/sticky obstruction'], ['responsive-layout', 'Responsive layout comparison']] as const;

export default function VisualResponsivePage() { const { selectedProject } = useProjects(); const [url, setUrl] = useState(''); const [sizes, setSizes] = useState<string[]>(['mobile', 'desktop']); const [selectedChecks, setSelectedChecks] = useState<string[]>(checks.map(([id]) => id)); const [scan, setScan] = useState<Scan | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const run = async () => { if (!selectedProject || !url.trim()) return; if (selectedChecks.includes('responsive-layout') && sizes.length < 2) { setError('Select at least two viewports for responsive comparison.'); return; } if (!selectedChecks.length) { setError('Select at least one visual check.'); return; } setBusy(true); setError(null); try { setScan(await createScan(selectedProject.id, { url, scope: 'single-page', module: 'visual-responsive', checks: selectedChecks, browsers: ['chromium'], viewports: sizes.map((size) => viewports[size as keyof typeof viewports]) })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to start visual validation.'); } finally { setBusy(false); } }; return <section className="scan-page"><p className="dashboard-eyebrow">QA CHECK · VISUAL</p><h1 className="dashboard-page-title">Visual &amp; Responsive</h1><p className="dashboard-lead">Find deterministic layout problems for any page URL.</p><div className="scan-config-card"><ScanTargetInput value={url} onChange={setUrl} error={error} /><h2>Checks</h2>{checks.map(([id, label]) => <label className="scan-check" key={id}><input type="checkbox" checked={selectedChecks.includes(id)} onChange={(event) => setSelectedChecks((current) => event.target.checked ? [...current, id] : current.filter((item) => item !== id))} /> <span>{label}</span></label>)}<h2>Viewports</h2>{Object.entries(viewports).map(([id, viewport]) => <label className="scan-check" key={id}><input type="checkbox" checked={sizes.includes(id)} onChange={(event) => setSizes((current) => event.target.checked ? [...current, id] : current.filter((item) => item !== id))} /> <span>{id} · {viewport.width} × {viewport.height}</span></label>)}{error && <p className="scan-inline-error" role="alert">{error}</p>}<button className="dashboard-primary-button" type="button" disabled={busy || !url.trim() || !selectedChecks.length || !sizes.length || !selectedProject} onClick={() => void run()}>{busy ? 'Starting…' : 'Run Visual Check'}</button></div>{scan && <div className="scan-confirmation" role="status"><p>{scan.target?.requestedUrl}</p><Link className="dashboard-card-action" href={`/scans/${scan.id}`}>View scan →</Link></div>}</section>; }
