'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { CreateEnvironmentRequest, Environment, EnvironmentType } from '@visionqa/contracts';
import { useProjects } from '@/features/projects/project-context';
import { environmentTypes } from '@/features/projects/project.validation';

const initialEnvironment: CreateEnvironmentRequest = { name: '', type: 'custom', baseUrl: '', isDefault: false };

function EnvironmentForm({ initial, submitLabel, onSubmit, onCancel }: { initial: CreateEnvironmentRequest; submitLabel: string; onSubmit: (value: CreateEnvironmentRequest) => Promise<void>; onCancel?: () => void }) {
  const [value, setValue] = useState(initial); const [saving, setSaving] = useState(false);
  const update = (key: keyof CreateEnvironmentRequest, next: string | boolean) => setValue((current) => ({ ...current, [key]: next }));
  return <form className="mt-4 grid gap-3 rounded-xl border border-fuchsia-200/70 bg-white/45 p-4 sm:grid-cols-2" onSubmit={async (event) => { event.preventDefault(); setSaving(true); await onSubmit(value); setSaving(false); }}><label className="grid gap-2 text-sm font-semibold text-[#542064]">Legacy environment name<input required className="liquid-control rounded-lg px-3 py-2 text-sm outline-none" placeholder="Production" value={value.name} onChange={(event) => update('name', event.target.value)} /></label><label className="grid gap-2 text-sm font-semibold text-[#542064]">Legacy target URL<input required type="url" className="liquid-control rounded-lg px-3 py-2 text-sm outline-none" placeholder="https://example.com" value={value.baseUrl} onChange={(event) => update('baseUrl', event.target.value)} /></label><label className="grid gap-2 text-sm font-semibold text-[#542064]">Type<select className="liquid-control rounded-lg px-3 py-2 text-sm outline-none" value={value.type} onChange={(event) => update('type', event.target.value as EnvironmentType)}>{environmentTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select></label><label className="flex items-center gap-2 self-end text-sm text-[#76527f]"><input type="checkbox" checked={value.isDefault} onChange={(event) => update('isDefault', event.target.checked)} /> Set as default for older scans</label><div className="flex gap-2 sm:col-span-2"><button className="liquid-primary rounded-lg px-4 py-2 text-sm font-semibold text-white disabled:opacity-60" disabled={saving} type="submit">{saving ? 'Saving…' : submitLabel}</button>{onCancel && <button className="rounded-lg border border-fuchsia-200 px-4 py-2 text-sm font-semibold text-[#76527f]" type="button" onClick={onCancel}>Cancel</button>}</div></form>;
}

function EnvironmentCard({ environment, onSave, onDelete }: { environment: Environment; onSave: (id: string, value: CreateEnvironmentRequest) => Promise<void>; onDelete: (id: string) => Promise<void> }) {
  const [editing, setEditing] = useState(false); if (editing) return <EnvironmentForm initial={{ name: environment.name, type: environment.type, baseUrl: environment.baseUrl, isDefault: environment.isDefault }} submitLabel="Save legacy configuration" onSubmit={async (value) => { await onSave(environment.id, value); setEditing(false); }} onCancel={() => setEditing(false)} />;
  return <div className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-fuchsia-200/70 bg-white/45 p-4"><div><div className="flex items-center gap-2 font-semibold text-[#542064]">{environment.name}{environment.isDefault && <span className="rounded-full bg-fuchsia-100 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-[#ad08d1]">Default</span>}</div><p className="mt-1 break-all text-sm text-[#76527f]">{environment.baseUrl}</p></div><div className="flex gap-2"><button className="rounded-lg border border-fuchsia-200 px-3 py-2 text-sm font-semibold text-[#ad08d1]" type="button" onClick={() => setEditing(true)}>Edit</button><button className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-600" type="button" onClick={() => { if (window.confirm('Delete this legacy environment configuration?')) void onDelete(environment.id); }}>Delete</button></div></div>;
}

export default function ProjectSettingsPage() {
  const router = useRouter(); const { selectedProject, saveProject, deleteSelectedProject, addEnvironment, saveEnvironment, removeEnvironment } = useProjects(); const [name, setName] = useState(selectedProject?.name ?? ''); const [adding, setAdding] = useState(false); const [message, setMessage] = useState<string | null>(null); const [deleting, setDeleting] = useState(false);
  useEffect(() => { setName(selectedProject?.name ?? ''); }, [selectedProject?.id, selectedProject?.name]); if (!selectedProject) return null;
  const saveName = async (event: React.FormEvent) => { event.preventDefault(); try { await saveProject(name); setMessage('Workspace settings saved.'); } catch { setMessage('Unable to save workspace settings.'); } };
  const add = async (value: CreateEnvironmentRequest) => { try { await addEnvironment(value); setAdding(false); setMessage('Legacy configuration added.'); } catch { setMessage('Unable to create legacy configuration.'); } };
  const edit = async (id: string, value: CreateEnvironmentRequest) => { try { await saveEnvironment(id, value); setMessage('Legacy configuration updated.'); } catch { setMessage('Unable to update legacy configuration.'); } };
  const remove = async (id: string) => { try { await removeEnvironment(id); setMessage('Legacy configuration deleted.'); } catch { setMessage('Unable to delete legacy configuration.'); } };
  const removeProject = async () => { if (!window.confirm(`Delete “${selectedProject.name}”? This permanently removes the project, scans, issues, and evidence.`)) return; setDeleting(true); try { await deleteSelectedProject(); router.replace('/dashboard'); } catch { setMessage('Unable to delete project. Please try again.'); setDeleting(false); } };
  return <section className="max-w-4xl"><p className="text-xs font-bold tracking-[0.2em] text-[#ad08d1]">CONFIGURATION</p><h1 className="mt-3 text-3xl font-bold text-[#32133f]">Project settings</h1><p className="mt-3 text-[#76527f]">Manage workspace identity and compatibility settings for older scans. New scans use a target URL selected at launch.</p>{message && <p className="mt-5 rounded-xl border border-fuchsia-200 bg-white/55 px-4 py-3 text-sm text-[#76527f]" role="status">{message}</p>}<div className="mt-8 space-y-8"><div className="rounded-2xl border border-fuchsia-200/70 bg-white/55 p-6"><h2 className="text-lg font-bold text-[#542064]">General</h2><form className="mt-5 max-w-xl space-y-4" onSubmit={saveName}><label className="block text-sm font-semibold text-[#542064]">Workspace name<input className="liquid-control mt-2 block w-full rounded-xl px-4 py-3 outline-none" value={name} onChange={(event) => setName(event.target.value)} /></label><button className="liquid-primary rounded-xl px-5 py-3 text-sm font-semibold text-white" type="submit">Save changes</button></form></div><div id="environments" className="rounded-2xl border border-fuchsia-200/70 bg-white/55 p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold tracking-[0.16em] text-[#ad08d1]">LEGACY CONFIGURATIONS</p><h2 className="mt-2 text-lg font-bold text-[#542064]">Environments</h2><p className="mt-1 text-sm text-[#76527f]">Used only to keep older environment-based scans readable. New scans do not require an environment.</p></div><button className="liquid-primary rounded-xl px-4 py-2 text-sm font-semibold text-white" type="button" onClick={() => setAdding((current) => !current)}>{adding ? 'Close' : '+ Add legacy config'}</button></div>{adding && <EnvironmentForm initial={initialEnvironment} submitLabel="Add legacy configuration" onSubmit={add} onCancel={() => setAdding(false)} />}<div className="mt-4 space-y-3">{selectedProject.environments.map((environment) => <EnvironmentCard key={environment.id} environment={environment} onSave={edit} onDelete={remove} />)}</div></div><div className="rounded-2xl border border-red-200/60 bg-red-50/35 p-6"><h2 className="text-lg font-bold text-red-800">Danger zone</h2><p className="mt-2 text-sm text-red-700/80">Permanently remove this project and all of its scans, issues, and evidence.</p><button className="mt-4 rounded-xl border border-red-300 px-4 py-2 text-sm font-bold text-red-700 hover:bg-red-100 disabled:cursor-not-allowed disabled:opacity-60" type="button" disabled={deleting} onClick={() => void removeProject()}>{deleting ? 'Deleting project…' : 'Delete project'}</button></div></div></section>;
}
