'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import type { Evidence, Issue } from '@visionqa/contracts';
import { getBrowserPages, getScanEvidence } from '../scan.service';
import { getIssues } from '@/features/issues/issue.service';
import { TargetUrlDisplay } from './TargetUrlDisplay';

export function InteractionResultsPanel({ projectId, scanId }: { projectId: string; scanId: string }) { const [issues, setIssues] = useState<Issue[]>([]); const [pages, setPages] = useState<Awaited<ReturnType<typeof getBrowserPages>>['executions']>([]); const [evidence, setEvidence] = useState<Evidence[]>([]); const [error, setError] = useState<string | null>(null); useEffect(() => { Promise.all([getIssues(projectId), getBrowserPages(projectId, scanId), getScanEvidence(projectId, scanId)]).then(([allIssues, pageResult, evidenceResult]) => { setIssues(allIssues.filter((issue) => issue.module === 'interactions-forms' && issue.scanIds?.includes(scanId))); setPages(pageResult.executions); setEvidence(evidenceResult.evidence.filter((item) => item.metadata?.interactionType)); }).catch(() => setError('Unable to load interaction results.')); }, [projectId, scanId]); return <div className="visual-results-panel"><p className="dashboard-eyebrow">INTERACTION RESULTS</p>{error && <p className="scan-error" role="alert">{error}</p>}<div className="scan-detail-card"><h2>Findings</h2>{issues.length ? <div className="scan-page-table">{issues.map((issue) => <Link className="scan-page-row" href={`/issues/${issue.id}`} key={issue.id}><div><strong>{issue.title}</strong><small>{issue.detectorId} · <TargetUrlDisplay url={issue.primaryUrl} /></small></div><span>{issue.severity}</span></Link>)}</div> : <p>No interaction failures or suspicious no-op controls were detected.</p>}</div><div className="scan-detail-card"><h2>Execution pages</h2>{pages.length ? <div className="scan-page-table">{pages.map((page) => <div className="scan-page-row" key={page.id}><div><strong><TargetUrlDisplay url={page.pageUrl} /></strong><small>{page.browser} · {page.viewport.width} × {page.viewport.height}</small></div><span>{page.status}</span></div>)}</div> : <p>No interaction execution pages are available.</p>}</div><div className="scan-detail-card"><h2>Interaction evidence</h2>{evidence.length ? evidence.map((item) => <div className="scan-page-row" key={item.id}><div><strong>{String(item.metadata?.evidenceRole ?? 'Screenshot')}</strong><small><TargetUrlDisplay url={item.pageUrl} /></small></div><span>{String(item.metadata?.interactionType ?? 'interaction')}</span></div>) : <p>Evidence is created for failed or non-working interactions.</p>}</div></div>; }
