import { chromium, firefox, webkit, type Browser, type Page } from 'playwright';
import type { BrowserFact, BrowserType, Viewport } from '@visionqa/contracts';
import type { BrowserScanJob } from '@visionqa/queue';
import { queueNames } from '@visionqa/queue';
import { Worker, type Job } from 'bullmq';
import { FirebaseBrowserExecutionRepository, FirebaseEvidenceRepository, FirebaseEvidenceStorage, FirebaseIssueRepository, FirebaseScanRepository } from '@visionqa/database/firebase';
import { NetworkPolicyError, OutboundNetworkPolicy } from '@visionqa/network-policy';
import { detectVisual } from '@visionqa/detectors';
import type { VisualPageSnapshot } from '@visionqa/contracts';

const maxMessages = 200;
const maxMessageLength = 2000;
const profiles: Record<string, Viewport> = { mobile: { width: 390, height: 844 }, tablet: { width: 768, height: 1024 }, desktop: { width: 1366, height: 768 }, wide: { width: 1920, height: 1080 } };
const truncate = (value: string) => value.slice(0, maxMessageLength);
const browserFor = (type: BrowserType) => type === 'firefox' ? firefox : type === 'webkit' ? webkit : chromium;
export function validateBrowserJob(job: BrowserScanJob): void { if (job.capability !== 'browser' || !job.scanId || !job.projectId || !job.targetUrl || !job.viewports.length) throw new Error('Invalid browser job.'); }

export class BrowserWorker {
  private readonly scans = new FirebaseScanRepository();
  private readonly executions = new FirebaseBrowserExecutionRepository();
  private readonly evidence = new FirebaseEvidenceStorage();
  private readonly evidenceRecords = new FirebaseEvidenceRepository();
  private readonly issues = new FirebaseIssueRepository();
  async start(): Promise<void> { const connection = { url: process.env.REDIS_URL ?? 'redis://127.0.0.1:6379' }; new Worker<BrowserScanJob>(queueNames.browser, (job) => this.process(job), { connection, concurrency: Number(process.env.BROWSER_CONCURRENCY ?? 1) }); console.log('VisionQA browser worker ready'); }
  validate(job: BrowserScanJob): void { validateBrowserJob(job); }
  private viewport(input: Viewport): Viewport { return input.width && input.height ? input : profiles.desktop!; }
  async process(job: Job<BrowserScanJob>): Promise<void> {
    this.validate(job.data); if (await this.scans.isCancellationRequested(job.data.scanId)) return;
    const policy = new OutboundNetworkPolicy(); await policy.validateAndResolve(job.data.targetUrl); const browserType: BrowserType = job.data.browsers[0] ?? 'chromium'; let browser: Browser | undefined;
    try { browser = await browserFor(browserType).launch({ headless: true }); let completed = 0;
      for (const requestedViewport of job.data.viewports) {
        if (await this.scans.isCancellationRequested(job.data.scanId)) return; const viewport = this.viewport(requestedViewport); const context = await browser.newContext({ viewport: { width: viewport.width, height: viewport.height }, ...(viewport.deviceScaleFactor ? { deviceScaleFactor: viewport.deviceScaleFactor } : {}) }); const execution = await this.executions.create({ scanId: job.data.scanId, projectId: job.data.projectId, pageUrl: job.data.targetUrl, browser: browserType, viewport, status: 'RUNNING', consoleErrorCount: 0, pageErrorCount: 0, failedRequestCount: 0 }); let page: Page | undefined; let collecting = true; let consoleErrors = 0; let pageErrors = 0; let failedRequests = 0; const started = Date.now(); const facts: Array<Omit<BrowserFact, 'id' | 'timestamp'>> = [];
        try {
          await context.route('**/*', async (route) => { const url = route.request().url(); if (url === 'about:blank') return route.continue(); try { const parsed = new URL(url); if (!['http:', 'https:'].includes(parsed.protocol)) throw new NetworkPolicyError('Unsupported browser request protocol'); await policy.validateAndResolve(url); await route.continue(); } catch (error) { if (collecting) facts.push({ scanId: job.data.scanId, executionId: execution.id, kind: 'NETWORK_POLICY_BLOCKED', url, resourceType: route.request().resourceType(), message: error instanceof Error ? truncate(error.message) : 'Request blocked by network policy' }); await route.abort('blockedbyclient'); } });
          page = await context.newPage(); page.on('console', (message) => { if (collecting && message.type() === 'error' && consoleErrors < maxMessages) { consoleErrors++; facts.push({ scanId: job.data.scanId, executionId: execution.id, kind: 'CONSOLE', type: message.type(), message: truncate(message.text()), source: message.location().url }); } }); page.on('pageerror', (error) => { if (collecting && pageErrors < maxMessages) { pageErrors++; facts.push({ scanId: job.data.scanId, executionId: execution.id, kind: 'PAGE_ERROR', message: truncate(error.message), source: truncate(error.stack ?? '') }); } }); page.on('request', (request) => { if (collecting && facts.length < maxMessages * 4) facts.push({ scanId: job.data.scanId, executionId: execution.id, kind: 'REQUEST', url: request.url(), type: request.method(), resourceType: request.resourceType() }); }); page.on('response', (response) => { if (collecting && facts.length < maxMessages * 4) facts.push({ scanId: job.data.scanId, executionId: execution.id, kind: 'RESPONSE', url: response.url(), status: response.status(), resourceType: response.request().resourceType() }); }); page.on('requestfailed', (request) => { if (collecting && failedRequests < maxMessages) { failedRequests++; facts.push({ scanId: job.data.scanId, executionId: execution.id, kind: 'FAILED_REQUEST', url: request.url(), resourceType: request.resourceType(), message: truncate(request.failure()?.errorText ?? 'Request failed') }); } });
          const response = await page.goto(job.data.targetUrl, { waitUntil: 'domcontentloaded', timeout: Number(process.env.BROWSER_NAVIGATION_TIMEOUT_MS ?? 30000) }); if (await this.scans.isCancellationRequested(job.data.scanId)) return; if (job.data.module === 'visual-responsive') await this.persistVisualFindings(job.data, await this.snapshot(page, job.data.scanId, execution.id, viewport)); const screenshot = await page.screenshot({ fullPage: true }); if (await this.scans.isCancellationRequested(job.data.scanId)) return; const storageKey = `projects/${job.data.projectId}/scans/${job.data.scanId}/browser/${execution.id}/${viewport.width}x${viewport.height}/screenshot.png`; await this.evidence.putObject(storageKey, { contentType: 'image/png', data: screenshot }); const evidence = await this.evidenceRecords.create({ projectId: job.data.projectId, scanId: job.data.scanId, executionId: execution.id, type: 'SCREENSHOT', storagePath: storageKey, contentType: 'image/png', sizeBytes: screenshot.byteLength, browser: browserType, viewport, pageUrl: page.url() }); if (await this.scans.isCancellationRequested(job.data.scanId)) return; await this.executions.markCompleted(job.data.scanId, execution.id, { status: 'COMPLETED', finalUrl: page.url(), ...(response?.status() !== undefined ? { httpStatus: response.status() } : {}), durationMs: Date.now() - started, consoleErrorCount: consoleErrors, pageErrorCount: pageErrors, failedRequestCount: failedRequests, screenshotEvidenceId: evidence.id });
        } catch { if (await this.scans.isCancellationRequested(job.data.scanId)) return; await this.executions.markCompleted(job.data.scanId, execution.id, { status: 'FAILED', durationMs: Date.now() - started, consoleErrorCount: consoleErrors, pageErrorCount: pageErrors, failedRequestCount: failedRequests }); } finally { collecting = false; await page?.close().catch(() => undefined); await context.close().catch(() => undefined); }
        completed++; if (await this.scans.isCancellationRequested(job.data.scanId)) return; await this.executions.addFacts(facts); await this.persistFindings(job.data, facts, viewport); await this.scans.updateProgress(job.data.scanId, { completed, total: job.data.viewports.length, percent: Math.round(completed / job.data.viewports.length * 100), processed: completed, pending: job.data.viewports.length - completed });
      } if (await this.scans.isCancellationRequested(job.data.scanId)) return; await this.scans.complete(job.data.scanId, { pagesChecked: completed, browser: browserType });
    } finally { await browser?.close().catch(() => undefined); }
  }
  private async persistFindings(job: BrowserScanJob, facts: Array<Omit<BrowserFact, 'id' | 'timestamp'>>, viewport: Viewport): Promise<void> { const enabled = new Set(job.checks); const candidates = facts.filter((fact) => (enabled.has('console-errors') && fact.kind === 'CONSOLE' && fact.type === 'error') || (enabled.has('javascript-errors') && fact.kind === 'PAGE_ERROR') || (enabled.has('failed-browser-requests') && fact.kind === 'FAILED_REQUEST') || (enabled.has('http-browser-errors') && fact.kind === 'RESPONSE' && (fact.status ?? 0) >= 400)); for (const fact of candidates.slice(0, maxMessages * 4)) { if (await this.scans.isCancellationRequested(job.scanId)) return; const detectorId = fact.kind === 'CONSOLE' ? 'console-errors' : fact.kind === 'PAGE_ERROR' ? 'javascript-errors' : fact.kind === 'FAILED_REQUEST' ? 'failed-browser-requests' : 'http-browser-errors'; const pageUrl = fact.url ?? job.targetUrl; await this.issues.upsertFinding({ projectId: job.projectId, detectorId, module: 'browser-network', severity: detectorId === 'javascript-errors' ? 'medium' : 'low', title: detectorId === 'http-browser-errors' ? 'Browser HTTP error' : detectorId === 'failed-browser-requests' ? 'Browser request failed' : detectorId === 'javascript-errors' ? 'JavaScript error on page' : 'Console error on page', message: truncate(fact.message ?? `Browser response returned HTTP ${fact.status ?? 'error'}.`), fingerprint: `${detectorId}|${pageUrl}|${fact.message ?? fact.status ?? ''}`, primaryUrl: pageUrl, scanId: job.scanId, evidence: { browser: job.browsers[0] ?? 'chromium', viewport, factKind: fact.kind, resourceUrl: fact.url, status: fact.status } }); } }
  private async snapshot(page: Page, scanId: string, executionId: string, viewport: Viewport): Promise<VisualPageSnapshot> { return page.evaluate(({ scanId: currentScanId, executionId: currentExecutionId, viewport: currentViewport }) => { const excluded = new Set(['SCRIPT', 'STYLE', 'META', 'LINK', 'HEAD', 'NOSCRIPT']); const elements = Array.from(document.querySelectorAll('*')).filter((node) => !excluded.has(node.tagName)).slice(0, 1000).map((node, index) => { const element = node as HTMLElement; const style = getComputedStyle(element); const rect = element.getBoundingClientRect(); const text = (element.innerText ?? '').trim().replace(/\s+/g, ' ').slice(0, 160); return { ref: `e${index}`, tagName: element.tagName.toLowerCase(), textPreview: text, ...(element.getAttribute('role') ? { role: element.getAttribute('role')! } : {}), selector: element.id ? `#${CSS.escape(element.id)}` : element.tagName.toLowerCase(), rect: { x: rect.x, y: rect.y, width: rect.width, height: rect.height }, display: style.display, visibility: style.visibility, position: style.position, overflow: style.overflow, zIndex: style.zIndex, fontSize: style.fontSize, lineHeight: style.lineHeight, whiteSpace: style.whiteSpace, interactive: /^(A|BUTTON|INPUT|SELECT|TEXTAREA|IMG|VIDEO|IFRAME)$/.test(element.tagName) || Boolean(element.getAttribute('role')) }; }).filter((element) => element.visibility !== 'hidden' && element.display !== 'none' && element.rect.width > 0 && element.rect.height > 0); return { scanId: currentScanId, executionId: currentExecutionId, pageUrl: location.href, browser: 'chromium', viewport: currentViewport, documentWidth: Math.max(document.documentElement.scrollWidth, document.body?.scrollWidth ?? 0), documentHeight: Math.max(document.documentElement.scrollHeight, document.body?.scrollHeight ?? 0), elements, capturedAt: new Date().toISOString() }; }, { scanId, executionId, viewport }) as Promise<VisualPageSnapshot>; }
  private async persistVisualFindings(job: BrowserScanJob, snapshot: VisualPageSnapshot): Promise<void> { for (const finding of detectVisual(snapshot, job.checks)) { if (await this.scans.isCancellationRequested(job.scanId)) return; await this.issues.upsertFinding({ projectId: job.projectId, detectorId: finding.detectorId, module: 'visual-responsive', severity: finding.severity, title: finding.title, message: finding.message, fingerprint: finding.fingerprint, primaryUrl: finding.pageUrl, scanId: job.scanId, evidence: { executionId: snapshot.executionId, browser: snapshot.browser, viewport: snapshot.viewport, elements: finding.elements } }); } }
}
