'use client';
import { useState } from 'react';
import Link from 'next/link';
import type { Scan } from '@visionqa/contracts';
import { ActiveQaTarget } from '@/features/projects/components/ActiveQaTarget';
import { useProjects } from '@/features/projects/project-context';
import { createScan } from '@/features/scans/scan.service';
import { ScanStatusBadge } from '@/features/scans/components/ScanStatusBadge';
const checks = [['console-errors', 'Console errors'], ['javascript-errors', 'JavaScript errors'], ['failed-browser-requests', 'Failed browser requests'], ['http-browser-errors', 'HTTP errors']] as const;
export default function BrowserNetworkPage() { const { selectedProject, selectedEnvironment } = useProjects(); const [selected, setSelected] = useState<string[]>(checks.map(([id]) => id)); const [viewports, setViewports] = useState<string[]>(['desktop']); const [scan, setScan] = useState<Scan | null>(null); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false); const profiles = { mobile: { width: 390, height: 844 }, tablet: { width: 768, height: 1024 }, desktop: { width: 1366, height: 768 }, wide: { width: 1920, height: 1080 } }; const start = async () => { if (!selectedProject || !selectedEnvironment || !selected.length || !viewports.length) return; setSubmitting(true); setError(null); try { setScan(await createScan(selectedProject.id, { environmentId: selectedEnvironment.id, module: 'browser-network', checks: selected, browsers: ['chromium'], viewports: viewports.map((profile) => profiles[profile as keyof typeof profiles]) })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to start browser validation.'); } finally { setSubmitting(false); } }; return <section className="scan-page"><p className="dashboard-eyebrow">QA CHECK · BROWSER</p><h1 className="dashboard-page-title">Browser &amp; Network</h1><p className="dashboard-lead">Run an isolated Chromium session and collect safe browser-runtime facts.</p><ActiveQaTarget /><div className="scan-config-card"><h2>Checks to run</h2>{checks.map(([id, label]) => <label className="scan-check" key={id}><input type="checkbox" checked={selected.includes(id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, id] : current.filter((item) => item !== id))} /> <span>{label}</span></label>)}<label className="scan-check"><span>Browser</span><strong>Chromium</strong></label><fieldset className="scan-check-group"><legend>Viewports</legend>{Object.entries(profiles).map(([id, profile]) => <label className="scan-check" key={id}><input type="checkbox" checked={viewports.includes(id)} onChange={(event) => setViewports((current) => event.target.checked ? [...current, id] : current.filter((item) => item !== id))} /> <span>{id[0]!.toUpperCase() + id.slice(1)} · {profile.width} × {profile.height}</span></label>)}</fieldset><button className="dashboard-primary-button" type="button" disabled={submitting || !selected.length || !viewports.length || !selectedProject || !selectedEnvironment} onClick={() => void start()}>{submitting ? 'Starting…' : 'Run Browser Check'}</button>{error && <p className="scan-error" role="alert">{error}</p>}</div>{scan && <div className="scan-confirmation" role="status"><div><h2>Scan queued</h2><p>{selectedEnvironment?.name} · {scan.checks.join(', ')}</p></div><ScanStatusBadge status={scan.status} /><Link className="dashboard-card-action" href={`/scans/${scan.id}`}>View scan <b>→</b></Link></div>}</section>; }
