export interface AccessibilityElement { ref: string; tagName: string; role?: string; type?: string; text: string; name: string; id?: string; required: boolean; disabled: boolean; tabIndex: number; visible: boolean; alt?: string; href?: string; rect: { x: number; y: number; width: number; height: number } }
export interface PageMetadataSnapshot { title: string; description: string; lang: string; canonical: string[]; robots: string; openGraph: Record<string, string>; hreflang: Array<{ lang: string; href: string }>; headings: Array<{ ref: string; level: number; text: string }>; duplicateIds: Array<{ id: string; refs: string[] }>; landmarks: Record<string, number>; elements: AccessibilityElement; images: AccessibilityElement[]; controls: AccessibilityElement[] }
export interface AccessibilityFinding { detectorId: string; severity: 'high' | 'medium' | 'low' | 'info'; title: string; message: string; elementRef?: string; ruleId?: string; metadata?: Record<string, string | number | boolean> }

const push = (out: AccessibilityFinding[], enabled: Set<string>, detectorId: string, finding: Omit<AccessibilityFinding, 'detectorId'>) => { if (enabled.has(detectorId)) out.push({ detectorId, ...finding }); };
export function analyzeAccessibilitySeo(snapshot: PageMetadataSnapshot, checks: string[]): AccessibilityFinding[] {
  const enabled = new Set(checks); const out: AccessibilityFinding[] = [];
  if (enabled.has('accessible-name')) for (const item of snapshot.controls.filter((control) => control.visible && !control.name && !['hidden', 'submit'].includes(control.type ?? ''))) push(out, enabled, 'accessible-name', { severity: 'high', title: 'Interactive control has no accessible name', message: `${item.tagName} does not expose a readable accessible name.`, elementRef: item.ref, ruleId: 'accessible-name' });
  if (enabled.has('form-labels')) for (const item of snapshot.controls.filter((control) => control.visible && ['input', 'select', 'textarea'].includes(control.tagName) && !['hidden', 'submit', 'button'].includes(control.type ?? '') && !control.name)) push(out, enabled, 'form-labels', { severity: 'high', title: 'Form control is missing a label', message: 'Associate this form control with a visible label, aria-label, or aria-labelledby.', elementRef: item.ref, ruleId: 'label' });
  if (enabled.has('image-alt')) for (const item of snapshot.images.filter((image) => image.visible && image.alt === undefined && image.role !== 'presentation')) push(out, enabled, 'image-alt', { severity: 'medium', title: 'Image is missing alternative text', message: 'Add alt text or mark the image as decorative when it conveys no information.', elementRef: item.ref, ruleId: 'image-alt' });
  if (enabled.has('duplicate-id')) for (const item of snapshot.duplicateIds) push(out, enabled, 'duplicate-id', { severity: 'medium', title: 'Duplicate id found', message: `The id “${item.id}” is used by ${item.refs.length} elements.`, ...(item.refs[0] ? { elementRef: item.refs[0] } : {}), ruleId: 'duplicate-id', metadata: { id: item.id, count: item.refs.length } });
  if (enabled.has('document-language') && !/^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$/.test(snapshot.lang)) push(out, enabled, 'document-language', { severity: 'medium', title: 'Document language is missing or invalid', message: 'Set a valid lang attribute on the html element.', ruleId: 'html-lang' });
  if (enabled.has('heading-structure')) for (const heading of snapshot.headings.filter((item) => !item.text || item.level < 1 || item.level > 6)) push(out, enabled, 'heading-structure', { severity: 'medium', title: 'Heading has invalid structure', message: 'Headings should have meaningful text and a valid level.', elementRef: heading.ref, ruleId: 'heading-structure' });
  if (enabled.has('landmark-structure') && !snapshot.landmarks.main) push(out, enabled, 'landmark-structure', { severity: 'low', title: 'Page has no main landmark', message: 'Add a main landmark around the page’s primary content.', ruleId: 'landmark' });
  if (enabled.has('keyboard-focus')) for (const item of snapshot.controls.filter((control) => control.visible && control.role && control.tabIndex < 0 && !control.disabled)) push(out, enabled, 'keyboard-focus', { severity: 'medium', title: 'Custom control is not keyboard focusable', message: 'Interactive custom controls should be reachable by keyboard.', elementRef: item.ref, ruleId: 'keyboard-focus' });
  if (enabled.has('seo-title') && !snapshot.title.trim()) push(out, enabled, 'seo-title', { severity: 'medium', title: 'Page title is missing', message: 'Add a descriptive title element.', ruleId: 'title' });
  if (enabled.has('meta-description') && !snapshot.description.trim()) push(out, enabled, 'meta-description', { severity: 'low', title: 'Meta description is missing', message: 'Add a concise meta description for this page.', ruleId: 'meta-description' });
  if (enabled.has('canonical') && snapshot.canonical.length !== 1) push(out, enabled, 'canonical', { severity: 'low', title: snapshot.canonical.length ? 'Multiple canonical URLs found' : 'Canonical URL is missing', message: snapshot.canonical.length ? 'Keep one canonical link for the page.' : 'Add a canonical link when the page has a preferred URL.', ruleId: 'canonical', metadata: { count: snapshot.canonical.length } });
  if (enabled.has('robots-meta') && !snapshot.robots.trim()) push(out, enabled, 'robots-meta', { severity: 'info', title: 'Robots metadata is not declared', message: 'No robots meta directive was found; crawlers use their default behavior.', ruleId: 'robots-meta' });
  if (enabled.has('indexability') && /\bnoindex\b/i.test(snapshot.robots)) push(out, enabled, 'indexability', { severity: 'info', title: 'Page is marked noindex', message: 'This page asks search engines not to index it.', ruleId: 'indexability' });
  if (enabled.has('open-graph')) for (const key of ['og:title', 'og:description', 'og:image', 'og:url']) if (!snapshot.openGraph[key]) push(out, enabled, 'open-graph', { severity: 'info', title: `Open Graph ${key.slice(3)} is missing`, message: `Add a ${key} value for richer link previews.`, ruleId: key });
  if (enabled.has('hreflang')) for (const item of snapshot.hreflang.filter((entry) => !entry.lang || !entry.href)) push(out, enabled, 'hreflang', { severity: 'low', title: 'Hreflang entry is incomplete', message: 'Each hreflang link needs a language and valid href.', ...(item.lang ? { elementRef: item.lang } : {}), ruleId: 'hreflang' });
  if (enabled.has('seo-heading-structure') && !snapshot.headings.some((heading) => heading.level === 1 && heading.text)) push(out, enabled, 'seo-heading-structure', { severity: 'low', title: 'Page has no descriptive H1', message: 'Add a descriptive primary heading for the page content.', ruleId: 'seo-heading' });
  if (enabled.has('seo-image-alt') && !enabled.has('image-alt')) for (const item of snapshot.images.filter((image) => image.visible && image.alt === undefined && image.role !== 'presentation')) push(out, enabled, 'seo-image-alt', { severity: 'low', title: 'Image alt coverage is incomplete', message: 'Add alternative text to meaningful images.', elementRef: item.ref, ruleId: 'image-alt' });
  return out.slice(0, 200);
}
