import type { BrowserFact, BrowserPageExecution, BrowserType, CompatibilityFinding, Viewport, VisualPageSnapshot } from '@visionqa/contracts';

type ExecutionInput = Pick<BrowserPageExecution, 'id' | 'pageUrl' | 'browser' | 'viewport' | 'status'>;
type VisualSignal = Pick<VisualPageSnapshot, 'pageUrl' | 'browser' | 'viewport' | 'documentWidth' | 'elements'>;

const volatileQuery = /^(utm_|fbclid$|gclid$|cacheBust$|timestamp$|nonce$|requestId$)/i;
const clamp = (value: string, size = 240) => value.slice(0, size);
const pageKey = (pageUrl: string, viewport: Viewport) => `${pageUrl}|${viewport.width}x${viewport.height}`;
const safeUrl = (value: string) => { try { const url = new URL(value); [...url.searchParams.keys()].filter((key) => volatileQuery.test(key)).forEach((key) => url.searchParams.delete(key)); return `${url.origin}${url.pathname}${url.search}`; } catch { return value.split('?')[0]!; } };
export function normalizeBrowserError(message: string | undefined): string { return clamp((message ?? 'Unknown browser error').replace(/https?:\/\/[^\s)]+/gi, '<url>').replace(/:\d+(?::\d+)?/g, ':line').replace(/\s+/g, ' ').trim()); }
export function normalizeRequestIdentity(url: string | undefined): string { return safeUrl(url ?? 'unknown-request'); }

export class BrowserCompatibilityComparisonService {
  compare(executions: ExecutionInput[], facts: BrowserFact[], visuals: VisualSignal[], checks: string[]): CompatibilityFinding[] {
    const selected = new Set(checks); const out: CompatibilityFinding[] = [];
    const groups = new Map<string, ExecutionInput[]>();
    for (const execution of executions) if (execution.status === 'COMPLETED') { const key = pageKey(safeUrl(execution.pageUrl), execution.viewport); groups.set(key, [...(groups.get(key) ?? []), execution]); }
    for (const [key, group] of groups) {
      if (group.length < 2) continue;
      const browsers = group.map((item) => item.browser); const groupFacts = facts.filter((fact) => group.some((item) => item.id === fact.executionId));
      if (selected.has('browser-console-differences')) this.compareConsole(key, group, groupFacts, browsers, out);
      if (selected.has('browser-request-differences')) this.compareRequests(key, group, groupFacts, browsers, out);
      if (selected.has('browser-render-differences')) this.compareRender(key, group, visuals, browsers, out);
      if (selected.has('browser-feature-failures')) this.compareFeatures(key, group, groupFacts, browsers, out);
    }
    return out.slice(0, 200);
  }
  private add(out: CompatibilityFinding[], detectorId: CompatibilityFinding['detectorId'], key: string, affectedBrowser: BrowserType, comparisonBrowsers: BrowserType[], signature: string, title: string, message: string, viewport: Viewport): void { const pageUrl = key.split('|')[0]!; out.push({ detectorId, pageUrl, viewport, affectedBrowser, comparisonBrowsers, differenceType: detectorId, normalizedSignature: signature, severity: detectorId === 'browser-console-differences' || detectorId === 'browser-feature-failures' ? 'high' : 'medium', title, message: clamp(message), fingerprint: `${detectorId}|${pageUrl}|${viewport.width}x${viewport.height}|${affectedBrowser}|${signature}` }); }
  private compareConsole(key: string, group: ExecutionInput[], facts: BrowserFact[], browsers: BrowserType[], out: CompatibilityFinding[]): void { const signatures = new Map<BrowserType, Set<string>>(); for (const browser of browsers) signatures.set(browser, new Set(facts.filter((fact) => group.find((item) => item.browser === browser)?.id === fact.executionId && (fact.kind === 'CONSOLE' || fact.kind === 'PAGE_ERROR')).map((fact) => normalizeBrowserError(fact.message)))); const all = new Set([...signatures.values()].flatMap((items) => [...items])); for (const signature of all) { const affected = browsers.filter((browser) => signatures.get(browser)?.has(signature)); if (!affected.length || affected.length === browsers.length) continue; for (const browser of affected) this.add(out, 'browser-console-differences', key, browser, browsers.filter((item) => item !== browser), signature, `${browser} reports a browser-specific console error`, `${browser} reported ${signature}, while the comparison browsers did not.`, group[0]!.viewport); } }
  private compareRequests(key: string, group: ExecutionInput[], facts: BrowserFact[], browsers: BrowserType[], out: CompatibilityFinding[]): void { const failed = new Map<BrowserType, Set<string>>(); for (const browser of browsers) failed.set(browser, new Set(facts.filter((fact) => group.find((item) => item.browser === browser)?.id === fact.executionId && fact.kind === 'FAILED_REQUEST').map((fact) => `${normalizeRequestIdentity(fact.url)}|${fact.resourceType ?? 'other'}`))); const all = new Set([...failed.values()].flatMap((items) => [...items])); for (const signature of all) { const affected = browsers.filter((browser) => failed.get(browser)?.has(signature)); if (!affected.length || affected.length === browsers.length) continue; for (const browser of affected) this.add(out, 'browser-request-differences', key, browser, browsers.filter((item) => item !== browser), signature, `${browser} has a browser-specific request failure`, `${browser} failed ${signature.split('|')[0]}, while the comparison browsers did not.`, group[0]!.viewport); } }
  private compareRender(key: string, group: ExecutionInput[], visuals: VisualSignal[], browsers: BrowserType[], out: CompatibilityFinding[]): void { const signals = new Map<BrowserType, Set<string>>(); for (const browser of browsers) { const visual = visuals.find((item) => item.browser === browser && pageKey(safeUrl(item.pageUrl), item.viewport) === key); const set = new Set<string>(); if (visual && visual.documentWidth > visual.viewport.width + 2) set.add('horizontal-overflow'); if (visual?.elements.some((item) => item.position === 'fixed' && (item.paintedAboveRefs?.length ?? 0) > 0)) set.add('fixed-element-obstruction'); signals.set(browser, set); } const all = new Set([...signals.values()].flatMap((items) => [...items])); for (const signature of all) { const affected = browsers.filter((browser) => signals.get(browser)?.has(signature)); if (!affected.length || affected.length === browsers.length) continue; for (const browser of affected) this.add(out, 'browser-render-differences', key, browser, browsers.filter((item) => item !== browser), signature, `${browser} has a browser-specific render signal`, `${browser} reported ${signature}, while the comparison browsers did not.`, group[0]!.viewport); } }
  private compareFeatures(key: string, group: ExecutionInput[], facts: BrowserFact[], browsers: BrowserType[], out: CompatibilityFinding[]): void { const featureErrors = facts.filter((fact) => fact.kind === 'PAGE_ERROR' && /not defined|unsupported|not implemented|failed to construct/i.test(fact.message ?? '')); for (const fact of featureErrors) { const browser = group.find((item) => item.id === fact.executionId)?.browser; if (!browser) continue; const signature = normalizeBrowserError(fact.message); const appearsElsewhere = facts.some((other) => other.executionId !== fact.executionId && normalizeBrowserError(other.message) === signature); if (!appearsElsewhere) this.add(out, 'browser-feature-failures', key, browser, browsers.filter((item) => item !== browser), signature, `${browser} reports a browser-specific feature failure`, `${browser} reported ${signature}.`, group[0]!.viewport); } }
}
