import type { QaModule } from '@visionqa/contracts';
export interface DetectorMetadata { id: string; name: string; module: QaModule; requirements: { browser?: boolean; dom?: boolean; http?: boolean; crawl?: boolean }; status: 'planned' | 'available' }
export const detectorCatalog: DetectorMetadata[] = [
  { id: 'crawl', name: 'Crawl website', module: 'crawl-site-structure', requirements: { crawl: true }, status: 'available' },
  { id: 'robots', name: 'Robots.txt', module: 'crawl-site-structure', requirements: { crawl: true }, status: 'available' },
  { id: 'sitemap', name: 'Sitemap', module: 'crawl-site-structure', requirements: { crawl: true }, status: 'available' },
  { id: 'redirect-analysis', name: 'Redirect analysis', module: 'crawl-site-structure', requirements: { crawl: true }, status: 'available' },
  { id: 'crawl-sitemap-comparison', name: 'Crawl vs sitemap comparison', module: 'crawl-site-structure', requirements: { crawl: true }, status: 'available' },
  { id: 'broken-internal-links', name: 'Broken internal links', module: 'links-resources', requirements: { http: true }, status: 'available' },
  { id: 'broken-external-links', name: 'Broken external links', module: 'links-resources', requirements: { http: true }, status: 'available' },
  { id: 'redirect-quality', name: 'Redirect quality', module: 'links-resources', requirements: { http: true }, status: 'available' },
  { id: 'broken-images', name: 'Broken images', module: 'links-resources', requirements: { http: true }, status: 'available' },
  { id: 'failed-scripts', name: 'Failed scripts', module: 'links-resources', requirements: { http: true }, status: 'available' },
  { id: 'failed-stylesheets', name: 'Failed stylesheets', module: 'links-resources', requirements: { http: true }, status: 'available' },
  { id: 'failed-fonts', name: 'Failed fonts', module: 'links-resources', requirements: { http: true }, status: 'available' },
  { id: 'failed-media', name: 'Failed media', module: 'links-resources', requirements: { http: true }, status: 'available' },
  { id: 'console-errors', name: 'Console errors', module: 'browser-network', requirements: { browser: true }, status: 'available' },
  { id: 'javascript-errors', name: 'JavaScript errors', module: 'browser-network', requirements: { browser: true }, status: 'available' },
  { id: 'failed-browser-requests', name: 'Failed browser requests', module: 'browser-network', requirements: { browser: true }, status: 'available' },
  { id: 'http-browser-errors', name: 'HTTP browser errors', module: 'browser-network', requirements: { browser: true }, status: 'available' },
  { id: 'text-overlap', name: 'Text overlap', module: 'visual-responsive', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'element-overlap', name: 'Element overlap', module: 'visual-responsive', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'clipped-content', name: 'Clipped content', module: 'visual-responsive', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'horizontal-overflow', name: 'Horizontal overflow', module: 'visual-responsive', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'viewport-overflow', name: 'Viewport overflow', module: 'visual-responsive', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'fixed-element-obstruction', name: 'Fixed/sticky obstruction', module: 'visual-responsive', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'responsive-layout', name: 'Responsive layout', module: 'visual-responsive', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'buttons', name: 'Buttons', module: 'interactions-forms', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'links-as-controls', name: 'Links behaving as controls', module: 'interactions-forms', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'menus', name: 'Menus', module: 'interactions-forms', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'tabs', name: 'Tabs', module: 'interactions-forms', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'accordions', name: 'Accordions', module: 'interactions-forms', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'dialogs', name: 'Dialogs and modals', module: 'interactions-forms', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'basic-form-validation', name: 'Basic form validation', module: 'interactions-forms', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'covered-controls', name: 'Covered controls', module: 'interactions-forms', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'disabled-controls', name: 'Disabled controls', module: 'interactions-forms', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'accessible-name', name: 'Accessible names', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'form-labels', name: 'Form labels', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'image-alt', name: 'Image alt text', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'heading-structure', name: 'Heading structure', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'document-language', name: 'Document language', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'duplicate-id', name: 'Duplicate IDs', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'landmark-structure', name: 'Landmark structure', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'keyboard-focus', name: 'Keyboard focus signals', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'seo-title', name: 'Page title', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'meta-description', name: 'Meta description', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'canonical', name: 'Canonical URL', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'robots-meta', name: 'Robots metadata', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'indexability', name: 'Indexability', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'open-graph', name: 'Open Graph', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'hreflang', name: 'Hreflang', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'seo-heading-structure', name: 'SEO heading metadata', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'seo-image-alt', name: 'SEO image alt coverage', module: 'accessibility-seo', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'navigation-performance', name: 'Navigation timing', module: 'performance-compatibility', requirements: { browser: true }, status: 'available' },
  { id: 'core-web-vitals', name: 'Core Web Vitals', module: 'performance-compatibility', requirements: { browser: true }, status: 'available' },
  { id: 'slow-resources', name: 'Slow resources', module: 'performance-compatibility', requirements: { browser: true }, status: 'available' },
  { id: 'large-resources', name: 'Large resources', module: 'performance-compatibility', requirements: { browser: true }, status: 'available' },
  { id: 'request-volume', name: 'Request volume', module: 'performance-compatibility', requirements: { browser: true }, status: 'available' },
  { id: 'transfer-size', name: 'Transfer size', module: 'performance-compatibility', requirements: { browser: true }, status: 'available' },
  { id: 'render-blocking', name: 'Render-blocking resources', module: 'performance-compatibility', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'image-performance', name: 'Image performance', module: 'performance-compatibility', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'browser-console-errors', name: 'Browser console differences', module: 'performance-compatibility', requirements: { browser: true }, status: 'available' },
  { id: 'browser-request-failures', name: 'Browser request differences', module: 'performance-compatibility', requirements: { browser: true }, status: 'available' },
  { id: 'browser-render-differences', name: 'Browser render differences', module: 'performance-compatibility', requirements: { browser: true, dom: true }, status: 'available' },
  { id: 'browser-feature-failures', name: 'Browser feature failures', module: 'performance-compatibility', requirements: { browser: true }, status: 'available' },
];
export class InMemoryDetectorRegistry {
  list(module?: QaModule): DetectorMetadata[] { return detectorCatalog.filter((detector) => !module || detector.module === module); }
  get(id: string): DetectorMetadata | undefined { return detectorCatalog.find((detector) => detector.id === id); }
}
