import type { VisualElement, VisualFinding, VisualPageSnapshot, VisualRect } from '@visionqa/contracts';

const tolerance = 4;
const cap = 50;
const visualTags = new Set(['A', 'BUTTON', 'INPUT', 'SELECT', 'TEXTAREA', 'FORM', 'NAV']);
const area = (a: VisualRect, b: VisualRect) => { const width = Math.max(0, Math.min(a.x + a.width, b.x + b.width) - Math.max(a.x, b.x)); const height = Math.max(0, Math.min(a.y + a.height, b.y + b.height) - Math.max(a.y, b.y)); return width * height; };
const overlapRatio = (a: VisualRect, b: VisualRect) => area(a, b) / Math.max(1, Math.min(a.width * a.height, b.width * b.height));
const descendant = (a: VisualElement, b: VisualElement) => a.ref !== b.ref && !a.selector.startsWith(`${b.selector} `) && !b.selector.startsWith(`${a.selector} `);
const meaningful = (a: VisualElement, b: VisualElement) => descendant(a, b) && overlapRatio(a.rect, b.rect) > 0.2;
const finding = (snapshot: VisualPageSnapshot, detectorId: string, title: string, message: string, severity: VisualFinding['severity'], elements: VisualElement[]): VisualFinding => ({ id: `${detectorId}-${snapshot.executionId}-${elements.map((item) => item.ref).join('-')}`, scanId: snapshot.scanId, executionId: snapshot.executionId, detectorId, pageUrl: snapshot.pageUrl, browser: snapshot.browser, viewport: snapshot.viewport, severity, title, message, fingerprint: `${detectorId}|${snapshot.pageUrl}|${elements.map((item) => item.ref).join('|')}`, elements: elements.map((item) => ({ ref: item.ref, selector: item.selector, rect: item.rect })) });

function pairs(snapshot: VisualPageSnapshot, detectorId: string, title: string, elements: VisualElement[]): VisualFinding[] { const findings: VisualFinding[] = []; for (let i = 0; i < elements.length && findings.length < cap; i++) for (let j = i + 1; j < elements.length && findings.length < cap; j++) { const first = elements[i]!; const second = elements[j]!; if (meaningful(first, second)) findings.push(finding(snapshot, detectorId, title, `${title} detected between ${first.textPreview || first.tagName} and ${second.textPreview || second.tagName}.`, 'medium', [first, second])); } return findings; }

function clipping(snapshot: VisualPageSnapshot): VisualFinding[] { const findings: VisualFinding[] = []; for (const item of snapshot.elements) { const overflowX = Math.max(0, (item.scrollWidth ?? 0) - (item.clientWidth ?? 0)); const overflowY = Math.max(0, (item.scrollHeight ?? 0) - (item.clientHeight ?? 0)); const clips = ['hidden', 'clip'].includes(item.overflow) || ['hidden', 'clip'].includes(item.overflowX ?? '') || ['hidden', 'clip'].includes(item.overflowY ?? ''); const intentional = item.textOverflow === 'ellipsis' || (item.lineClamp && item.lineClamp !== 'none') || ['auto', 'scroll'].includes(item.overflow); if (!clips || intentional || !item.textPreview || (overflowX <= tolerance && overflowY <= tolerance)) continue; const amount = [overflowX > tolerance ? `${overflowX}px horizontally` : '', overflowY > tolerance ? `${overflowY}px vertically` : ''].filter(Boolean).join(' and '); findings.push(finding(snapshot, 'clipped-content', 'Visible content is clipped', `${item.textPreview} is clipped by ${amount} inside ${item.selector}.`, 'medium', [item])); if (findings.length >= cap) break; } return findings; }

function obstruction(snapshot: VisualPageSnapshot): VisualFinding[] { const fixed = snapshot.elements.filter((item) => item.position === 'fixed' || item.position === 'sticky'); const targets = snapshot.elements.filter((item) => item.interactive || visualTags.has(item.tagName.toUpperCase())); const findings: VisualFinding[] = []; for (const overlay of fixed) for (const target of targets) { if (findings.length >= cap || overlay.ref === target.ref || !meaningful(overlay, target)) continue; if (overlay.role === 'dialog' || overlay.tagName === 'dialog' || overlay.role === 'alertdialog') continue; if (!(overlay.paintedAboveRefs ?? []).includes(target.ref)) continue; findings.push(finding(snapshot, 'fixed-element-obstruction', 'Fixed element obstructs content', `${overlay.textPreview || overlay.tagName} obstructs ${target.textPreview || target.tagName} at the ${snapshot.viewport.width}px viewport.`, 'high', [overlay, target])); } return findings; }

const responsiveChecks = ['text-overlap', 'element-overlap', 'clipped-content', 'horizontal-overflow', 'viewport-overflow', 'fixed-element-obstruction'];
export function compareVisualViewports(results: Array<{ snapshot: VisualPageSnapshot; findings: VisualFinding[] }>): VisualFinding[] { if (results.length < 2) return []; const bySignal = new Map<string, VisualFinding[]>(); for (const result of results) for (const item of result.findings) { if (!responsiveChecks.includes(item.detectorId)) continue; const key = `${item.detectorId}|${item.pageUrl}|${item.elements.map((element) => element.selector).sort().join('|')}`; const group = bySignal.get(key) ?? []; group.push(item); bySignal.set(key, group); } const findings: VisualFinding[] = []; for (const group of bySignal.values()) { const viewports = new Set(group.map((item) => `${item.viewport.width}x${item.viewport.height}`)); if (viewports.size === results.length) continue; const representative = group[0]!; findings.push({ ...representative, id: `responsive-layout-${representative.scanId}-${representative.executionId}-${findings.length}`, detectorId: 'responsive-layout', title: 'Layout changes across viewports', message: `${representative.title} appears at ${[...viewports].join(', ')} but not consistently across the selected viewports.`, fingerprint: `responsive-layout|${representative.pageUrl}|${representative.elements.map((element) => element.selector).sort().join('|')}`, elements: representative.elements }); if (findings.length >= cap) break; } return findings; }

export function detectVisual(snapshot: VisualPageSnapshot, checks: string[]): VisualFinding[] { const visible = snapshot.elements; const findings: VisualFinding[] = []; if (checks.includes('text-overlap')) findings.push(...pairs(snapshot, 'text-overlap', 'Text overlap', visible.filter((item) => Boolean(item.textPreview)))); if (checks.includes('element-overlap')) findings.push(...pairs(snapshot, 'element-overlap', 'Interactive elements overlap', visible.filter((item) => item.interactive))); if (checks.includes('clipped-content')) findings.push(...clipping(snapshot)); if (checks.includes('horizontal-overflow') && snapshot.documentWidth > snapshot.viewport.width + tolerance) { const overflow = visible.filter((item) => item.rect.x + item.rect.width > snapshot.viewport.width + tolerance || item.rect.x < -tolerance).slice(0, 5); findings.push(finding(snapshot, 'horizontal-overflow', 'Horizontal page overflow', `The page is ${snapshot.documentWidth - snapshot.viewport.width}px wider than the viewport.`, 'medium', overflow)); } if (checks.includes('viewport-overflow')) for (const item of visible.filter((candidate) => candidate.interactive && (candidate.rect.x < -tolerance || candidate.rect.x + candidate.rect.width > snapshot.viewport.width + tolerance)).slice(0, cap)) findings.push(finding(snapshot, 'viewport-overflow', 'Element is outside the viewport', `${item.textPreview || item.tagName} is not fully accessible within the viewport.`, 'medium', [item])); if (checks.includes('fixed-element-obstruction')) findings.push(...obstruction(snapshot)); return findings.slice(0, cap); }
